// ── Clue bank ────────────────────────────────────────────────────────────
// Answers must be single, unbroken words (no spaces) — they get placed
// letter-by-letter into the grid. Clue text has no such restriction and can
// use normal accented characters freely.
// Hebrew: final letters (ם ן ף ך ץ) are normalized to base forms (מ נ פ כ צ)
// at grid-build time — same rule as wordsearch-strings.js's normalizeHebrew(),
// for the same reason (a final form could otherwise collide with a base
// form at a shared intersection cell).
// Spanish: answers avoid accented vowels and ñ so every letter matches
// cleanly at intersections (no accent-normalization helper needed).
const CLUE_BANK = {
  animals: {
    en: [
      { answer: 'LION', clue: 'King of the jungle', difficulty: 'easy' },
      { answer: 'TIGER', clue: 'Large striped big cat', difficulty: 'easy' },
      { answer: 'ELEPHANT', clue: 'Largest land animal, has a trunk', difficulty: 'easy' },
      { answer: 'BEAR', clue: 'Large, furry animal that hibernates in winter', difficulty: 'easy' },
      { answer: 'ZEBRA', clue: 'Black-and-white striped horse-like animal', difficulty: 'easy' },
      { answer: 'MONKEY', clue: 'Primate that loves bananas', difficulty: 'easy' },
      { answer: 'PENGUIN', clue: 'Flightless bird that lives in the cold', difficulty: 'easy' },
      { answer: 'DOLPHIN', clue: 'Intelligent marine mammal that clicks and whistles', difficulty: 'easy' },
      { answer: 'EAGLE', clue: 'Bird of prey with sharp eyesight', difficulty: 'easy' },
      { answer: 'RABBIT', clue: 'Long-eared hopping animal', difficulty: 'easy' },
      { answer: 'SNAKE', clue: 'Legless reptile that slithers', difficulty: 'easy' },
      { answer: 'TURTLE', clue: 'Reptile with a hard shell', difficulty: 'easy' },
      { answer: 'WOLF', clue: 'Wild canine that howls at the moon', difficulty: 'easy' },
      { answer: 'CAMEL', clue: 'Desert animal with humps', difficulty: 'easy' },
      { answer: 'KANGAROO', clue: 'Australian animal that hops and carries its young in a pouch', difficulty: 'easy' },
      { answer: 'OCTOPUS', clue: 'Eight-armed sea creature with three hearts', difficulty: 'hard' },
      { answer: 'CHAMELEON', clue: 'Lizard that changes color to blend in', difficulty: 'hard' },
      { answer: 'RHINOCEROS', clue: 'Large thick-skinned animal with a horn on its nose', difficulty: 'hard' },
      { answer: 'ARMADILLO', clue: 'Armored mammal that can roll into a ball', difficulty: 'hard' },
      { answer: 'FLAMINGO', clue: 'Pink wading bird that stands on one leg', difficulty: 'hard' },
      { answer: 'HEDGEHOG', clue: 'Small spiny mammal that curls into a ball', difficulty: 'hard' },
      { answer: 'PANDA', clue: 'Black-and-white bear that eats mostly bamboo', difficulty: 'medium' },
      { answer: 'GORILLA', clue: 'Large great ape found in African forests', difficulty: 'medium' },
      { answer: 'OSTRICH', clue: 'Largest bird in the world, cannot fly', difficulty: 'medium' },
      { answer: 'SQUIRREL', clue: 'Small bushy-tailed rodent that collects nuts', difficulty: 'medium' },
      { answer: 'BUTTERFLY', clue: 'Insect with colorful wings that starts life as a caterpillar', difficulty: 'medium' }
    ],
    he: [
      { answer: 'אריה', clue: 'מלך החיות', difficulty: 'easy' },
      { answer: 'טיגריס', clue: 'חתול גדול עם פסים', difficulty: 'easy' },
      { answer: 'פיל', clue: 'בעל החיים היבשתי הגדול בעולם, יש לו חדק', difficulty: 'easy' },
      { answer: 'דוב', clue: 'בעל חיים גדול ופרוותי שנכנס לחורף', difficulty: 'easy' },
      { answer: 'זברה', clue: 'דומה לסוס עם פסים שחורים ולבנים', difficulty: 'easy' },
      { answer: 'קוף', clue: 'פרימט שאוהב בננות', difficulty: 'easy' },
      { answer: 'פינגווין', clue: 'ציפור שלא עפה וחיה בקור', difficulty: 'easy' },
      { answer: 'דולפין', clue: 'יונק ים חכם המשמיע קליקים ושריקות', difficulty: 'easy' },
      { answer: 'נשר', clue: 'עוף דורס עם ראייה חדה', difficulty: 'easy' },
      { answer: 'ארנב', clue: 'בעל חיים עם אוזניים ארוכות שמקפץ', difficulty: 'easy' },
      { answer: 'נחש', clue: 'זוחל בלי רגליים שמתפתל', difficulty: 'easy' },
      { answer: 'צב', clue: 'זוחל עם שריון קשה', difficulty: 'easy' },
      { answer: 'זאב', clue: 'כלביים ברי שמייללים ללבנה', difficulty: 'easy' },
      { answer: 'גמל', clue: 'בעל חיים מדברי עם דבשות', difficulty: 'easy' },
      { answer: 'קנגורו', clue: 'בעל חיים אוסטרלי שמקפץ ונושא גורים בכיס', difficulty: 'easy' },
      { answer: 'תמנון', clue: 'יצור ימי בעל שמונה זרועות ושלושה לבבות', difficulty: 'hard' },
      { answer: 'זיקית', clue: 'לטאה המחליפה צבע כדי להיטמע בסביבה', difficulty: 'hard' },
      { answer: 'קרנף', clue: 'חיה גדולה בעלת עור עבה וקרן על האף', difficulty: 'hard' },
      { answer: 'ארמדילו', clue: 'יונק משוריין שמסוגל להתגלגל לכדור', difficulty: 'hard' },
      { answer: 'פלמינגו', clue: 'עוף ורוד החי במים רדודים ועומד על רגל אחת', difficulty: 'hard' },
      { answer: 'קיפוד', clue: 'יונק קטן וקוצני שמתכרבל לכדור', difficulty: 'hard' },
      { answer: 'פנדה', clue: 'דוב שחור-לבן שאוכל בעיקר במבוק', difficulty: 'medium' },
      { answer: 'גורילה', clue: 'קוף אדם גדול החי ביערות אפריקה', difficulty: 'medium' },
      { answer: 'יען', clue: 'הציפור הגדולה בעולם, לא יכולה לעוף', difficulty: 'medium' },
      { answer: 'סנאי', clue: 'מכרסם קטן בעל זנב שעיר שאוסף אגוזים', difficulty: 'medium' },
      { answer: 'פרפר', clue: 'חרק בעל כנפיים צבעוניות שמתחיל את חייו כזחל', difficulty: 'medium' }
    ],
    es: [
      { answer: 'LEON', clue: 'Rey de la selva', difficulty: 'easy' },
      { answer: 'TIGRE', clue: 'Gran felino con rayas', difficulty: 'easy' },
      { answer: 'ELEFANTE', clue: 'El animal terrestre más grande, tiene trompa', difficulty: 'easy' },
      { answer: 'OSO', clue: 'Animal grande y peludo que hiberna en invierno', difficulty: 'easy' },
      { answer: 'CEBRA', clue: 'Animal con rayas blancas y negras', difficulty: 'easy' },
      { answer: 'MONO', clue: 'Primate que ama los plátanos', difficulty: 'easy' },
      { answer: 'PINGUINO', clue: 'Ave que no vuela y vive en el frío', difficulty: 'easy' },
      { answer: 'DELFIN', clue: 'Mamífero marino inteligente', difficulty: 'easy' },
      { answer: 'AGUILA', clue: 'Ave de presa con vista muy aguda', difficulty: 'easy' },
      { answer: 'CONEJO', clue: 'Animal de orejas largas que salta', difficulty: 'easy' },
      { answer: 'SERPIENTE', clue: 'Reptil sin patas que se arrastra', difficulty: 'easy' },
      { answer: 'TORTUGA', clue: 'Reptil con caparazón duro', difficulty: 'easy' },
      { answer: 'LOBO', clue: 'Cánido salvaje que aúlla a la luna', difficulty: 'easy' },
      { answer: 'CAMELLO', clue: 'Animal del desierto con jorobas', difficulty: 'easy' },
      { answer: 'CANGURO', clue: 'Animal australiano que salta y lleva crías en una bolsa', difficulty: 'easy' },
      { answer: 'PULPO', clue: 'Criatura marina con ocho brazos y tres corazones', difficulty: 'hard' },
      { answer: 'CAMALEON', clue: 'Lagarto que cambia de color para camuflarse', difficulty: 'hard' },
      { answer: 'RINOCERONTE', clue: 'Animal grande de piel gruesa con un cuerno en la nariz', difficulty: 'hard' },
      { answer: 'ARMADILLO', clue: 'Mamífero acorazado que puede enrollarse en forma de bola', difficulty: 'hard' },
      { answer: 'FLAMENCO', clue: 'Ave rosada que vive en aguas poco profundas y se para en una pata', difficulty: 'hard' },
      { answer: 'ERIZO', clue: 'Pequeño mamífero espinoso que se enrolla en forma de bola', difficulty: 'hard' },
      { answer: 'PANDA', clue: 'Oso blanco y negro que come principalmente bambú', difficulty: 'medium' },
      { answer: 'GORILA', clue: 'Gran simio que vive en los bosques de África', difficulty: 'medium' },
      { answer: 'AVESTRUZ', clue: 'El ave más grande del mundo, no puede volar', difficulty: 'medium' },
      { answer: 'ARDILLA', clue: 'Pequeño roedor de cola peluda que recolecta nueces', difficulty: 'medium' },
      { answer: 'MARIPOSA', clue: 'Insecto de alas coloridas que comienza su vida como oruga', difficulty: 'medium' }
    ]
  },
  food: {
    en: [
      { answer: 'BREAD', clue: 'Baked staple made from flour', difficulty: 'easy' },
      { answer: 'AVOCADO', clue: 'Creamy green fruit used to make guacamole', difficulty: 'easy' },
      { answer: 'PIZZA', clue: 'Italian baked dish of dough topped with sauce and toppings', difficulty: 'easy' },
      { answer: 'PASTA', clue: 'Italian noodles', difficulty: 'easy' },
      { answer: 'RICE', clue: 'Staple grain eaten worldwide', difficulty: 'easy' },
      { answer: 'TOFU', clue: 'Soft protein-rich food made from soybeans', difficulty: 'easy' },
      { answer: 'LENTIL', clue: 'Small round legume often used in soups', difficulty: 'easy' },
      { answer: 'LEMON', clue: 'Sour yellow citrus fruit', difficulty: 'easy' },
      { answer: 'GARLIC', clue: 'Pungent bulb used for flavoring', difficulty: 'easy' },
      { answer: 'ONION', clue: 'Layered bulb that makes you cry when cut', difficulty: 'easy' },
      { answer: 'TOMATO', clue: 'Red fruit used in salads and sauces', difficulty: 'easy' },
      { answer: 'BANANA', clue: 'Long yellow tropical fruit', difficulty: 'easy' },
      { answer: 'CHOCOLATE', clue: 'Sweet treat made from cacao', difficulty: 'easy' },
      { answer: 'SYRUP', clue: 'Sweet, thick liquid poured on pancakes, often made from maple sap', difficulty: 'easy' },
      { answer: 'SALAD', clue: 'Mix of raw vegetables', difficulty: 'easy' },
      { answer: 'ARTICHOKE', clue: 'Thistle-like vegetable eaten leaf by leaf', difficulty: 'hard' },
      { answer: 'POMEGRANATE', clue: 'Red fruit filled with juicy seed clusters', difficulty: 'hard' },
      { answer: 'ASPARAGUS', clue: 'Green stalk vegetable often grilled or steamed', difficulty: 'hard' },
      { answer: 'CINNAMON', clue: 'Spice made from tree bark, used in baking', difficulty: 'hard' },
      { answer: 'WATERMELON', clue: 'Large green fruit with red juicy flesh and seeds', difficulty: 'hard' },
      { answer: 'EGGPLANT', clue: 'Purple oblong vegetable used in ratatouille and baba ganoush', difficulty: 'hard' },
      { answer: 'SPINACH', clue: 'Leafy green vegetable rich in iron', difficulty: 'medium' },
      { answer: 'MUSHROOM', clue: 'Fungus often sliced as a pizza topping', difficulty: 'medium' },
      { answer: 'COCONUT', clue: 'Large brown tropical fruit with white flesh and milk inside', difficulty: 'medium' },
      { answer: 'PINEAPPLE', clue: 'Spiky tropical fruit with a crown of leaves on top', difficulty: 'medium' },
      { answer: 'PEPPER', clue: 'Vegetable that comes in red, green, and yellow varieties', difficulty: 'medium' }
    ],
    he: [
      { answer: 'לחם', clue: 'מאכל בסיסי אפוי העשוי מקמח', difficulty: 'easy' },
      { answer: 'אבוקדו', clue: 'פרי ירוק ושמנוני שממנו מכינים גואקמולי', difficulty: 'easy' },
      { answer: 'פיצה', clue: 'מאכל איטלקי אפוי העשוי מבצק עם רוטב ותוספות', difficulty: 'easy' },
      { answer: 'פסטה', clue: 'אטריות איטלקיות', difficulty: 'easy' },
      { answer: 'אורז', clue: 'דגן בסיסי הנאכל בכל העולם', difficulty: 'easy' },
      { answer: 'טופו', clue: 'מאכל רך ועשיר בחלבון העשוי מפולי סויה', difficulty: 'easy' },
      { answer: 'עדשה', clue: 'קטנית עגולה וקטנה המשמשת לרוב במרקים', difficulty: 'easy' },
      { answer: 'לימון', clue: 'פרי הדר צהוב וחמוץ', difficulty: 'easy' },
      { answer: 'שום', clue: 'בצל חריף המשמש לתיבול', difficulty: 'easy' },
      { answer: 'בצל', clue: 'ירק שכבתי שמגרה דמעות בחיתוך', difficulty: 'easy' },
      { answer: 'עגבניה', clue: 'פרי אדום המשמש בסלטים ורטבים', difficulty: 'easy' },
      { answer: 'בננה', clue: 'פרי טרופי צהוב וארוך', difficulty: 'easy' },
      { answer: 'שוקולד', clue: 'ממתק העשוי מקקאו', difficulty: 'easy' },
      { answer: 'סירופ', clue: 'נוזל מתוק וסמיך שיוצקים על פנקייק, לרוב עשוי ממיץ עץ המייפל', difficulty: 'easy' },
      { answer: 'סלט', clue: 'תערובת של ירקות טריים', difficulty: 'easy' },
      { answer: 'ארטישוק', clue: 'ירק דמוי קוץ שאוכלים עלה אחר עלה', difficulty: 'hard' },
      { answer: 'רימון', clue: 'פרי אדום מלא בגרגרים עסיסיים', difficulty: 'hard' },
      { answer: 'אספרגוס', clue: 'ירק גבעולי ירוק שלעיתים קרובות צולים או מאדים', difficulty: 'hard' },
      { answer: 'קינמון', clue: 'תבלין העשוי מקליפת עץ, משמש באפייה', difficulty: 'hard' },
      { answer: 'אבטיח', clue: 'פרי גדול וירוק עם בשר אדום ועסיסי וגרעינים', difficulty: 'hard' },
      { answer: 'חציל', clue: 'ירק סגול ומוארך המשמש ברטטוי ובבבא גנוש', difficulty: 'hard' },
      { answer: 'תרד', clue: 'ירק עלים ירוק עשיר בברזל', difficulty: 'medium' },
      { answer: 'פטרייה', clue: 'מאכל הגדל ביערות, לא צמח ולא בעל חיים, נפוץ כתוספת לפיצה', difficulty: 'medium' },
      { answer: 'קוקוס', clue: 'פרי טרופי חום וגדול עם בשר לבן וחלב בפנים', difficulty: 'medium' },
      { answer: 'אננס', clue: 'פרי טרופי קוצני עם כתר עלים בראשו', difficulty: 'medium' },
      { answer: 'פלפל', clue: 'ירק שמגיע בגוונים אדום, ירוק וצהוב', difficulty: 'medium' }
    ],
    es: [
      { answer: 'PAN', clue: 'Alimento básico horneado hecho de harina', difficulty: 'easy' },
      { answer: 'AGUACATE', clue: 'Fruta verde y cremosa usada para hacer guacamole', difficulty: 'easy' },
      { answer: 'PIZZA', clue: 'Plato italiano horneado hecho de masa con salsa y coberturas', difficulty: 'easy' },
      { answer: 'PASTA', clue: 'Fideos italianos', difficulty: 'easy' },
      { answer: 'ARROZ', clue: 'Grano básico comido en todo el mundo', difficulty: 'easy' },
      { answer: 'TOFU', clue: 'Alimento suave y rico en proteína hecho de soja', difficulty: 'easy' },
      { answer: 'LENTEJA', clue: 'Legumbre pequeña y redonda usada a menudo en sopas', difficulty: 'easy' },
      { answer: 'LIMON', clue: 'Fruta cítrica amarilla y ácida', difficulty: 'easy' },
      { answer: 'AJO', clue: 'Bulbo picante usado para dar sabor', difficulty: 'easy' },
      { answer: 'CEBOLLA', clue: 'Bulbo que hace llorar al cortarlo', difficulty: 'easy' },
      { answer: 'TOMATE', clue: 'Fruta roja usada en ensaladas y salsas', difficulty: 'easy' },
      { answer: 'PLATANO', clue: 'Fruta tropical larga y amarilla', difficulty: 'easy' },
      { answer: 'CHOCOLATE', clue: 'Dulce hecho de cacao', difficulty: 'easy' },
      { answer: 'JARABE', clue: 'Líquido dulce y espeso que se vierte sobre panqueques, a menudo hecho de savia de arce', difficulty: 'easy' },
      { answer: 'ENSALADA', clue: 'Mezcla de verduras crudas', difficulty: 'easy' },
      { answer: 'ALCACHOFA', clue: 'Verdura parecida a un cardo que se come hoja por hoja', difficulty: 'hard' },
      { answer: 'GRANADA', clue: 'Fruta roja llena de racimos de semillas jugosas', difficulty: 'hard' },
      { answer: 'ESPARRAGO', clue: 'Verdura de tallo verde que suele asarse o cocerse al vapor', difficulty: 'hard' },
      { answer: 'CANELA', clue: 'Especia hecha de corteza de árbol, usada en repostería', difficulty: 'hard' },
      { answer: 'SANDIA', clue: 'Fruta grande y verde con pulpa roja y jugosa y semillas', difficulty: 'hard' },
      { answer: 'BERENJENA', clue: 'Verdura morada y alargada usada en ratatouille y baba ganoush', difficulty: 'hard' },
      { answer: 'ESPINACA', clue: 'Verdura de hoja verde rica en hierro', difficulty: 'medium' },
      { answer: 'HONGO', clue: 'Organismo comestible, ni planta ni animal, usado como ingrediente en pizzas', difficulty: 'medium' },
      { answer: 'COCO', clue: 'Fruta tropical grande y marrón con pulpa blanca y agua dentro', difficulty: 'medium' },
      { answer: 'ANANAS', clue: 'Fruta tropical espinosa con una corona de hojas en la parte superior', difficulty: 'medium' },
      { answer: 'PIMIENTO', clue: 'Verdura que viene en variedades roja, verde y amarilla', difficulty: 'medium' }
    ]
  },
  sports: {
    en: [
      { answer: 'SOCCER', clue: 'Sport played with a ball, mostly without hands', difficulty: 'easy' },
      { answer: 'TENNIS', clue: 'Racket sport played across a net', difficulty: 'easy' },
      { answer: 'BOXING', clue: 'Combat sport fought with fists', difficulty: 'easy' },
      { answer: 'GOLF', clue: 'Sport where you hit a small ball into holes', difficulty: 'easy' },
      { answer: 'HOCKEY', clue: 'Sport played with a stick and a puck', difficulty: 'easy' },
      { answer: 'RUGBY', clue: 'Contact sport with an oval ball', difficulty: 'easy' },
      { answer: 'SURFING', clue: 'Riding ocean waves on a board', difficulty: 'easy' },
      { answer: 'CYCLING', clue: 'Racing or riding on a bicycle', difficulty: 'easy' },
      { answer: 'SWIMMING', clue: 'Racing through water without a board', difficulty: 'easy' },
      { answer: 'BOWLING', clue: 'Knocking down pins with a heavy ball', difficulty: 'easy' },
      { answer: 'ARCHERY', clue: 'Sport of shooting arrows at a target', difficulty: 'easy' },
      { answer: 'FENCING', clue: 'Combat sport fought with swords', difficulty: 'easy' },
      { answer: 'SKIING', clue: 'Gliding downhill on snow with two long boards', difficulty: 'easy' },
      { answer: 'WRESTLING', clue: 'Combat sport of grappling and pins', difficulty: 'easy' },
      { answer: 'CLIMBING', clue: 'Sport of scaling rock walls or mountains', difficulty: 'easy' },
      { answer: 'BADMINTON', clue: 'Racket sport played with a shuttlecock', difficulty: 'hard' },
      { answer: 'GYMNASTICS', clue: 'Sport of flips, balance beams, and floor routines', difficulty: 'hard' },
      { answer: 'TRIATHLON', clue: 'Race combining swimming, cycling, and running', difficulty: 'hard' },
      { answer: 'VOLLEYBALL', clue: 'Team sport played by hitting a ball over a net', difficulty: 'hard' },
      { answer: 'HANDBALL', clue: 'Team sport where players throw a ball into a goal by hand', difficulty: 'hard' },
      { answer: 'KARATE', clue: 'Japanese martial art of striking with hands and feet', difficulty: 'hard' },
      { answer: 'CRICKET', clue: 'Bat-and-ball sport popular in England and India', difficulty: 'medium' },
      { answer: 'RUNNING', clue: 'Sport of moving fast on foot, from sprints to marathons', difficulty: 'medium' },
      { answer: 'SAILING', clue: 'Sport of racing boats powered by wind', difficulty: 'medium' },
      { answer: 'DIVING', clue: 'Sport of jumping or descending into water', difficulty: 'medium' },
      { answer: 'BASKETBALL', clue: 'Team sport played by shooting a ball through a hoop', difficulty: 'medium' }
    ],
    he: [
      { answer: 'כדורגל', clue: 'ספורט המשוחק בכדור, בעיקר בלי ידיים', difficulty: 'easy' },
      { answer: 'טניס', clue: 'ספורט מחבטים המשוחק מעל רשת', difficulty: 'easy' },
      { answer: 'אגרוף', clue: 'ספורט קרב הנלחם באגרופים', difficulty: 'easy' },
      { answer: 'גולף', clue: 'ספורט של הכנסת כדור קטן לחורים', difficulty: 'easy' },
      { answer: 'הוקי', clue: 'ספורט המשוחק עם מקל ודיסקית', difficulty: 'easy' },
      { answer: 'רוגבי', clue: 'ספורט מגע עם כדור סגלגל', difficulty: 'easy' },
      { answer: 'גלישה', clue: 'רכיבה על גלי האוקיינוס בעזרת גלשן', difficulty: 'easy' },
      { answer: 'רכיבה', clue: 'תחרות או נסיעה על אופניים', difficulty: 'easy' },
      { answer: 'שחייה', clue: 'תחרות במים בלי גלשן', difficulty: 'easy' },
      { answer: 'באולינג', clue: 'הפלת כרעיים בעזרת כדור כבד', difficulty: 'easy' },
      { answer: 'קשתות', clue: 'ספורט של ירי חצים לעבר מטרה', difficulty: 'easy' },
      { answer: 'סייף', clue: 'ספורט קרב עם חרבות', difficulty: 'easy' },
      { answer: 'סקי', clue: 'גלישה במורד על שלג בעזרת שני מגלשים', difficulty: 'easy' },
      { answer: 'היאבקות', clue: 'ספורט קרב של תפיסות והצמדות', difficulty: 'easy' },
      { answer: 'טיפוס', clue: 'ספורט של טיפוס על קירות סלע או הרים', difficulty: 'easy' },
      { answer: 'בדמינטון', clue: 'ספורט מחבטים המשוחק עם נוצית', difficulty: 'hard' },
      { answer: 'התעמלות', clue: 'ספורט של סלטות, קורת שיווי משקל ותרגילי רצפה', difficulty: 'hard' },
      { answer: 'טריאתלון', clue: 'תחרות המשלבת שחייה, רכיבה על אופניים וריצה', difficulty: 'hard' },
      { answer: 'כדורעף', clue: 'ספורט קבוצתי המשוחק בהכאת כדור מעל רשת', difficulty: 'hard' },
      { answer: 'כדוריד', clue: 'ספורט קבוצתי שבו שחקנים זורקים כדור לשער בעזרת היד', difficulty: 'hard' },
      { answer: 'קראטה', clue: 'אמנות לחימה יפנית של הכאה בידיים וברגליים', difficulty: 'hard' },
      { answer: 'קריקט', clue: 'ספורט מחבט וכדור פופולרי באנגליה ובהודו', difficulty: 'medium' },
      { answer: 'ריצה', clue: 'ספורט של תנועה מהירה ברגל, מספרינטים ועד מרתונים', difficulty: 'medium' },
      { answer: 'שייט', clue: 'ספורט של מרוצי סירות המונעות ברוח', difficulty: 'medium' },
      { answer: 'צלילה', clue: 'ספורט של קפיצה או ירידה למים', difficulty: 'medium' },
      { answer: 'כדורסל', clue: 'ספורט קבוצתי המשוחק בהכנסת כדור לסל', difficulty: 'medium' }
    ],
    es: [
      { answer: 'FUTBOL', clue: 'Deporte que se juega con un balón, casi sin usar las manos', difficulty: 'easy' },
      { answer: 'TENIS', clue: 'Deporte de raqueta que se juega sobre una red', difficulty: 'easy' },
      { answer: 'BOXEO', clue: 'Deporte de combate con los puños', difficulty: 'easy' },
      { answer: 'GOLF', clue: 'Deporte de golpear una pequeña bola hacia hoyos', difficulty: 'easy' },
      { answer: 'HOCKEY', clue: 'Deporte que se juega con un palo y un disco', difficulty: 'easy' },
      { answer: 'RUGBY', clue: 'Deporte de contacto con un balón ovalado', difficulty: 'easy' },
      { answer: 'SURF', clue: 'Deslizarse sobre las olas del mar en una tabla', difficulty: 'easy' },
      { answer: 'CICLISMO', clue: 'Correr o andar en bicicleta', difficulty: 'easy' },
      { answer: 'NATACION', clue: 'Nadar en competencia sin tabla', difficulty: 'easy' },
      { answer: 'BOLOS', clue: 'Derribar bolos con una bola pesada', difficulty: 'easy' },
      { answer: 'ARQUERIA', clue: 'Deporte de disparar flechas a un blanco', difficulty: 'easy' },
      { answer: 'ESGRIMA', clue: 'Deporte de combate con espadas', difficulty: 'easy' },
      { answer: 'ESQUI', clue: 'Deslizarse cuesta abajo en la nieve', difficulty: 'easy' },
      { answer: 'LUCHA', clue: 'Deporte de combate de agarres', difficulty: 'easy' },
      { answer: 'ESCALADA', clue: 'Deporte de subir muros de roca o montañas', difficulty: 'easy' },
      { answer: 'BADMINTON', clue: 'Deporte de raqueta que se juega con un volante', difficulty: 'hard' },
      { answer: 'GIMNASIA', clue: 'Deporte de saltos, barra de equilibrio y ejercicios de suelo', difficulty: 'hard' },
      { answer: 'TRIATLON', clue: 'Carrera que combina natación, ciclismo y carrera a pie', difficulty: 'hard' },
      { answer: 'VOLEIBOL', clue: 'Deporte de equipo que se juega golpeando un balón sobre una red', difficulty: 'hard' },
      { answer: 'BALONMANO', clue: 'Deporte de equipo donde los jugadores lanzan un balón a la portería con la mano', difficulty: 'hard' },
      { answer: 'KARATE', clue: 'Arte marcial japonés de golpear con las manos y los pies', difficulty: 'hard' },
      { answer: 'CRICKET', clue: 'Deporte de bate y pelota popular en Inglaterra e India', difficulty: 'medium' },
      { answer: 'CARRERA', clue: 'Deporte de moverse rápido a pie, desde sprints hasta maratones', difficulty: 'medium' },
      { answer: 'VELA', clue: 'Deporte de carreras de barcos impulsados por el viento', difficulty: 'medium' },
      { answer: 'BUCEO', clue: 'Deporte de saltar o descender al agua', difficulty: 'medium' },
      { answer: 'BALONCESTO', clue: 'Deporte de equipo que se juega lanzando un balón por un aro', difficulty: 'medium' }
    ]
  },
  science: {
    en: [
      { answer: 'ATOM', clue: 'Smallest unit of matter', difficulty: 'easy' },
      { answer: 'ENERGY', clue: 'Capacity to do work', difficulty: 'easy' },
      { answer: 'GRAVITY', clue: 'Force that pulls objects toward Earth', difficulty: 'easy' },
      { answer: 'OXYGEN', clue: 'Gas humans need to breathe', difficulty: 'easy' },
      { answer: 'CELL', clue: 'Basic unit of life', difficulty: 'easy' },
      { answer: 'VIRUS', clue: 'Microscopic infectious agent', difficulty: 'easy' },
      { answer: 'PLANET', clue: 'Large body orbiting a star', difficulty: 'easy' },
      { answer: 'GALAXY', clue: 'Huge system of stars, like the Milky Way', difficulty: 'easy' },
      { answer: 'MAGNET', clue: 'Object that attracts iron', difficulty: 'easy' },
      { answer: 'VACCINE', clue: 'Shot that trains the immune system', difficulty: 'easy' },
      { answer: 'CHEMISTRY', clue: 'Science of matter and reactions', difficulty: 'easy' },
      { answer: 'BIOLOGY', clue: 'Science of living things', difficulty: 'easy' },
      { answer: 'FOSSIL', clue: 'Preserved remains of ancient life', difficulty: 'easy' },
      { answer: 'BACTERIA', clue: 'Single-celled microorganisms', difficulty: 'easy' },
      { answer: 'ELECTRON', clue: 'Negatively charged subatomic particle', difficulty: 'easy' },
      { answer: 'PHOTOSYNTHESIS', clue: 'Process plants use to turn sunlight into energy', difficulty: 'hard' },
      { answer: 'EVOLUTION', clue: 'Gradual change in species over generations', difficulty: 'hard' },
      { answer: 'MOLECULE', clue: 'Smallest unit of a chemical compound', difficulty: 'hard' },
      { answer: 'ECOSYSTEM', clue: 'Community of organisms interacting with their environment', difficulty: 'hard' },
      { answer: 'RADIATION', clue: 'Energy that travels as waves or particles', difficulty: 'hard' },
      { answer: 'HORMONE', clue: 'Chemical messenger produced by glands in the body', difficulty: 'hard' },
      { answer: 'FRICTION', clue: 'Force that resists motion between two surfaces', difficulty: 'medium' },
      { answer: 'TELESCOPE', clue: 'Instrument used to observe distant objects in space', difficulty: 'medium' },
      { answer: 'ORBIT', clue: 'Curved path an object follows around another due to gravity', difficulty: 'medium' },
      { answer: 'CRYSTAL', clue: 'Solid with atoms arranged in a repeating pattern', difficulty: 'medium' },
      { answer: 'METEOR', clue: 'Streak of light from a space rock burning in the atmosphere', difficulty: 'medium' }
    ],
    he: [
      { answer: 'אטום', clue: 'היחידה הקטנה ביותר של החומר', difficulty: 'easy' },
      { answer: 'אנרגיה', clue: 'היכולת לבצע עבודה', difficulty: 'easy' },
      { answer: 'כבידה', clue: 'הכוח המושך חפצים לכיוון כדור הארץ', difficulty: 'easy' },
      { answer: 'חמצן', clue: 'הגז שבני אדם צריכים לנשום', difficulty: 'easy' },
      { answer: 'תא', clue: 'יחידת היסוד של החיים', difficulty: 'easy' },
      { answer: 'נגיף', clue: 'גורם מדבק מיקרוסקופי', difficulty: 'easy' },
      { answer: 'פלנטה', clue: 'גוף גדול המקיף כוכב', difficulty: 'easy' },
      { answer: 'גלקסיה', clue: 'מערכת עצומה של כוכבים', difficulty: 'easy' },
      { answer: 'מגנט', clue: 'חפץ המושך ברזל', difficulty: 'easy' },
      { answer: 'חיסון', clue: 'זריקה שמאמנת את מערכת החיסון', difficulty: 'easy' },
      { answer: 'כימיה', clue: 'מדע החומר והתגובות שלו', difficulty: 'easy' },
      { answer: 'ביולוגיה', clue: 'מדע היצורים החיים', difficulty: 'easy' },
      { answer: 'מאובן', clue: 'שרידים משומרים של חיים קדומים', difficulty: 'easy' },
      { answer: 'חיידק', clue: 'מיקרואורגניזם חד-תאי', difficulty: 'easy' },
      { answer: 'אלקטרון', clue: 'חלקיק תת-אטומי בעל מטען שלילי', difficulty: 'easy' },
      { answer: 'פוטוסינתזה', clue: 'התהליך שבו צמחים הופכים אור שמש לאנרגיה', difficulty: 'hard' },
      { answer: 'אבולוציה', clue: 'שינוי הדרגתי במינים לאורך דורות', difficulty: 'hard' },
      { answer: 'מולקולה', clue: 'היחידה הקטנה ביותר של תרכובת כימית', difficulty: 'hard' },
      { answer: 'אקוסיסטמה', clue: 'קהילת יצורים המקיימת אינטראקציה עם סביבתה', difficulty: 'hard' },
      { answer: 'קרינה', clue: 'אנרגיה הנעה בצורת גלים או חלקיקים', difficulty: 'hard' },
      { answer: 'הורמון', clue: 'שליח כימי המיוצר על ידי בלוטות בגוף', difficulty: 'hard' },
      { answer: 'חיכוך', clue: 'כוח המתנגד לתנועה בין שתי משטחים', difficulty: 'medium' },
      { answer: 'טלסקופ', clue: 'מכשיר המשמש לצפייה בעצמים רחוקים בחלל', difficulty: 'medium' },
      { answer: 'מסלול', clue: 'מסלול מעוקל שגוף עוקב אחריו סביב גוף אחר בגלל הכבידה', difficulty: 'medium' },
      { answer: 'גביש', clue: 'מוצק שבו האטומים מסודרים בתבנית חוזרת', difficulty: 'medium' },
      { answer: 'מטאור', clue: 'פס אור הנוצר משביט המתלקח באטמוספרה', difficulty: 'medium' }
    ],
    es: [
      { answer: 'ATOMO', clue: 'La unidad más pequeña de la materia', difficulty: 'easy' },
      { answer: 'ENERGIA', clue: 'Capacidad de realizar trabajo', difficulty: 'easy' },
      { answer: 'GRAVEDAD', clue: 'Fuerza que atrae los objetos hacia la Tierra', difficulty: 'easy' },
      { answer: 'OXIGENO', clue: 'Gas que los humanos necesitan para respirar', difficulty: 'easy' },
      { answer: 'CELULA', clue: 'Unidad básica de la vida', difficulty: 'easy' },
      { answer: 'VIRUS', clue: 'Agente infeccioso microscópico', difficulty: 'easy' },
      { answer: 'PLANETA', clue: 'Gran cuerpo que orbita una estrella', difficulty: 'easy' },
      { answer: 'GALAXIA', clue: 'Enorme sistema de estrellas', difficulty: 'easy' },
      { answer: 'IMAN', clue: 'Objeto que atrae el hierro', difficulty: 'easy' },
      { answer: 'VACUNA', clue: 'Inyección que entrena el sistema inmune', difficulty: 'easy' },
      { answer: 'QUIMICA', clue: 'Ciencia de la materia y sus reacciones', difficulty: 'easy' },
      { answer: 'BIOLOGIA', clue: 'Ciencia de los seres vivos', difficulty: 'easy' },
      { answer: 'FOSIL', clue: 'Restos conservados de vida antigua', difficulty: 'easy' },
      { answer: 'BACTERIA', clue: 'Microorganismo de una sola célula', difficulty: 'easy' },
      { answer: 'ELECTRON', clue: 'Partícula subatómica con carga negativa', difficulty: 'easy' },
      { answer: 'FOTOSINTESIS', clue: 'Proceso que usan las plantas para convertir la luz solar en energía', difficulty: 'hard' },
      { answer: 'EVOLUCION', clue: 'Cambio gradual en las especies a lo largo de generaciones', difficulty: 'hard' },
      { answer: 'MOLECULA', clue: 'Unidad más pequeña de un compuesto químico', difficulty: 'hard' },
      { answer: 'ECOSISTEMA', clue: 'Comunidad de organismos que interactúan con su entorno', difficulty: 'hard' },
      { answer: 'RADIACION', clue: 'Energía que viaja en forma de ondas o partículas', difficulty: 'hard' },
      { answer: 'HORMONA', clue: 'Mensajero químico producido por las glándulas del cuerpo', difficulty: 'hard' },
      { answer: 'FRICCION', clue: 'Fuerza que se opone al movimiento entre dos superficies', difficulty: 'medium' },
      { answer: 'TELESCOPIO', clue: 'Instrumento usado para observar objetos distantes en el espacio', difficulty: 'medium' },
      { answer: 'ORBITA', clue: 'Trayectoria curva que sigue un objeto alrededor de otro por la gravedad', difficulty: 'medium' },
      { answer: 'CRISTAL', clue: 'Sólido con átomos organizados en un patrón repetitivo', difficulty: 'medium' },
      { answer: 'METEORO', clue: 'Rastro de luz de una roca espacial que se quema en la atmósfera', difficulty: 'medium' }
    ]
  },
  geography: {
    en: [
      { answer: 'FRANCE', clue: 'European country famous for the Eiffel Tower', difficulty: 'easy' },
      { answer: 'JAPAN', clue: 'Island nation known as the Land of the Rising Sun', difficulty: 'easy' },
      { answer: 'BRAZIL', clue: 'Largest country in South America', difficulty: 'easy' },
      { answer: 'EGYPT', clue: 'Country famous for pyramids and the Nile', difficulty: 'easy' },
      { answer: 'CANADA', clue: 'Country north of the United States', difficulty: 'easy' },
      { answer: 'ITALY', clue: 'Boot-shaped country famous for pasta', difficulty: 'easy' },
      { answer: 'MEXICO', clue: 'Country south of the United States', difficulty: 'easy' },
      { answer: 'RUSSIA', clue: 'Largest country in the world by area', difficulty: 'easy' },
      { answer: 'CHINA', clue: 'Most populous country in Asia', difficulty: 'easy' },
      { answer: 'INDIA', clue: 'Country famous for the Taj Mahal', difficulty: 'easy' },
      { answer: 'GREECE', clue: 'Birthplace of the Olympic Games', difficulty: 'easy' },
      { answer: 'PERU', clue: 'Home to Machu Picchu and the Andes', difficulty: 'easy' },
      { answer: 'TURKEY', clue: 'Country that bridges Europe and Asia', difficulty: 'easy' },
      { answer: 'GERMANY', clue: 'European country known for Oktoberfest', difficulty: 'easy' },
      { answer: 'ISRAEL', clue: 'Country in the Middle East along the Mediterranean', difficulty: 'easy' },
      { answer: 'ARGENTINA', clue: 'South American country famous for tango', difficulty: 'hard' },
      { answer: 'AUSTRALIA', clue: 'Country and continent known for kangaroos and koalas', difficulty: 'hard' },
      { answer: 'NORWAY', clue: 'Scandinavian country known for fjords and the midnight sun', difficulty: 'hard' },
      { answer: 'THAILAND', clue: 'Southeast Asian country known as the Land of Smiles', difficulty: 'hard' },
      { answer: 'MOROCCO', clue: 'North African country known for its markets and the Sahara', difficulty: 'hard' },
      { answer: 'ICELAND', clue: 'Nordic island nation of volcanoes and glaciers', difficulty: 'hard' },
      { answer: 'PORTUGAL', clue: 'European country west of Spain, known for Porto and fado music', difficulty: 'medium' },
      { answer: 'VIETNAM', clue: 'Southeast Asian country known for Ha Long Bay and pho soup', difficulty: 'medium' },
      { answer: 'KENYA', clue: 'East African country famous for safaris and long-distance runners', difficulty: 'medium' },
      { answer: 'SWEDEN', clue: 'Scandinavian country known for IKEA and Nobel Prizes', difficulty: 'medium' },
      { answer: 'COLOMBIA', clue: 'South American country known for coffee and Cartagena', difficulty: 'medium' }
    ],
    he: [
      { answer: 'צרפת', clue: 'מדינה אירופית ידועה במגדל אייפל', difficulty: 'easy' },
      { answer: 'יפן', clue: 'מדינת אי המכונה ארץ השמש העולה', difficulty: 'easy' },
      { answer: 'ברזיל', clue: 'המדינה הגדולה ביותר בדרום אמריקה', difficulty: 'easy' },
      { answer: 'מצרים', clue: 'מדינה ידועה בפירמידות ובנילוס', difficulty: 'easy' },
      { answer: 'קנדה', clue: 'מדינה שנמצאת מצפון לארצות הברית', difficulty: 'easy' },
      { answer: 'איטליה', clue: 'מדינה בצורת מגף, ידועה בפסטה', difficulty: 'easy' },
      { answer: 'מקסיקו', clue: 'מדינה שנמצאת מדרום לארצות הברית', difficulty: 'easy' },
      { answer: 'רוסיה', clue: 'המדינה הגדולה בעולם בשטח', difficulty: 'easy' },
      { answer: 'סין', clue: 'המדינה המאוכלסת ביותר באסיה', difficulty: 'easy' },
      { answer: 'הודו', clue: 'מדינה ידועה בטאג מהאל', difficulty: 'easy' },
      { answer: 'יוון', clue: 'מקום הולדתם של המשחקים האולימפיים', difficulty: 'easy' },
      { answer: 'פרו', clue: 'ביתם של מאצו פיצ׳ו והרי האנדים', difficulty: 'easy' },
      { answer: 'טורקיה', clue: 'מדינה המקשרת בין אירופה לאסיה', difficulty: 'easy' },
      { answer: 'גרמניה', clue: 'מדינה אירופית ידועה באוקטוברפסט', difficulty: 'easy' },
      { answer: 'ישראל', clue: 'מדינה במזרח התיכון על חוף הים התיכון', difficulty: 'easy' },
      { answer: 'ארגנטינה', clue: 'מדינה בדרום אמריקה הידועה בריקוד הטנגו', difficulty: 'hard' },
      { answer: 'אוסטרליה', clue: 'מדינה ויבשת הידועה בקנגורו ובקואלה', difficulty: 'hard' },
      { answer: 'נורווגיה', clue: 'מדינה סקנדינבית הידועה בפיורדים ובשמש חצות', difficulty: 'hard' },
      { answer: 'תאילנד', clue: 'מדינה בדרום מזרח אסיה המכונה ארץ החיוכים', difficulty: 'hard' },
      { answer: 'מרוקו', clue: 'מדינה בצפון אפריקה הידועה בשווקים שלה ובמדבר סהרה', difficulty: 'hard' },
      { answer: 'איסלנד', clue: 'מדינת אי נורדית של הרי געש וקרחונים', difficulty: 'hard' },
      { answer: 'פורטוגל', clue: 'מדינה אירופית ממערב לספרד, ידועה בפורטו ובמוזיקת פאדו', difficulty: 'medium' },
      { answer: 'וייטנאם', clue: 'מדינה בדרום מזרח אסיה הידועה במפרץ הלונג ובמרק פו', difficulty: 'medium' },
      { answer: 'קניה', clue: 'מדינה במזרח אפריקה הידועה בספארי וברצי מרחקים ארוכים', difficulty: 'medium' },
      { answer: 'שוודיה', clue: 'מדינה סקנדינבית הידועה באיקאה ובפרסי נובל', difficulty: 'medium' },
      { answer: 'קולומביה', clue: 'מדינה בדרום אמריקה הידועה בקפה ובקרטחנה', difficulty: 'medium' }
    ],
    es: [
      { answer: 'FRANCIA', clue: 'País europeo famoso por la Torre Eiffel', difficulty: 'easy' },
      { answer: 'JAPON', clue: 'Nación insular conocida como la Tierra del Sol Naciente', difficulty: 'easy' },
      { answer: 'BRASIL', clue: 'El país más grande de Sudamérica', difficulty: 'easy' },
      { answer: 'EGIPTO', clue: 'País famoso por sus pirámides y el río Nilo', difficulty: 'easy' },
      { answer: 'CANADA', clue: 'País al norte de Estados Unidos', difficulty: 'easy' },
      { answer: 'ITALIA', clue: 'País con forma de bota, famoso por la pasta', difficulty: 'easy' },
      { answer: 'MEXICO', clue: 'País al sur de Estados Unidos', difficulty: 'easy' },
      { answer: 'RUSIA', clue: 'El país más grande del mundo por área', difficulty: 'easy' },
      { answer: 'CHINA', clue: 'El país más poblado de Asia', difficulty: 'easy' },
      { answer: 'INDIA', clue: 'País famoso por el Taj Mahal', difficulty: 'easy' },
      { answer: 'GRECIA', clue: 'Cuna de los Juegos Olímpicos', difficulty: 'easy' },
      { answer: 'PERU', clue: 'Hogar de Machu Picchu y los Andes', difficulty: 'easy' },
      { answer: 'TURQUIA', clue: 'País que conecta Europa y Asia', difficulty: 'easy' },
      { answer: 'ALEMANIA', clue: 'País europeo conocido por el Oktoberfest', difficulty: 'easy' },
      { answer: 'ISRAEL', clue: 'País de Oriente Medio junto al Mediterráneo', difficulty: 'easy' },
      { answer: 'ARGENTINA', clue: 'País sudamericano famoso por el tango', difficulty: 'hard' },
      { answer: 'AUSTRALIA', clue: 'País y continente conocido por los canguros y koalas', difficulty: 'hard' },
      { answer: 'NORUEGA', clue: 'País escandinavo conocido por sus fiordos y el sol de medianoche', difficulty: 'hard' },
      { answer: 'TAILANDIA', clue: 'País del sudeste asiático conocido como la Tierra de las Sonrisas', difficulty: 'hard' },
      { answer: 'MARRUECOS', clue: 'País del norte de África conocido por sus mercados y el Sahara', difficulty: 'hard' },
      { answer: 'ISLANDIA', clue: 'Nación insular nórdica de volcanes y glaciares', difficulty: 'hard' },
      { answer: 'PORTUGAL', clue: 'País europeo al oeste de España, conocido por Oporto y el fado', difficulty: 'medium' },
      { answer: 'VIETNAM', clue: 'País del sudeste asiático conocido por la bahía de Ha Long y la sopa pho', difficulty: 'medium' },
      { answer: 'KENIA', clue: 'País de África oriental famoso por los safaris y los corredores de fondo', difficulty: 'medium' },
      { answer: 'SUECIA', clue: 'País escandinavo conocido por IKEA y los premios Nobel', difficulty: 'medium' },
      { answer: 'COLOMBIA', clue: 'País sudamericano conocido por el café y Cartagena', difficulty: 'medium' }
    ]
  },
  colors: {
    en: [
      { answer: 'RED', clue: 'Color of blood or a stop sign', difficulty: 'easy' },
      { answer: 'BLUE', clue: 'Color of a clear sky', difficulty: 'easy' },
      { answer: 'GREEN', clue: 'Color of grass', difficulty: 'easy' },
      { answer: 'YELLOW', clue: 'Color of a lemon', difficulty: 'easy' },
      { answer: 'BLACK', clue: 'Color of night, the absence of light', difficulty: 'easy' },
      { answer: 'WHITE', clue: 'Color of snow', difficulty: 'easy' },
      { answer: 'PURPLE', clue: 'Color made by mixing red and blue', difficulty: 'easy' },
      { answer: 'ORANGE', clue: 'Color named after a citrus fruit', difficulty: 'easy' },
      { answer: 'PINK', clue: 'Pale reddish color, often linked to roses', difficulty: 'easy' },
      { answer: 'BROWN', clue: 'Color of coffee or tree bark', difficulty: 'easy' },
      { answer: 'GRAY', clue: 'Color between black and white', difficulty: 'easy' },
      { answer: 'GOLD', clue: 'Shiny yellow metallic color', difficulty: 'easy' },
      { answer: 'SILVER', clue: 'Shiny grayish metallic color', difficulty: 'easy' },
      { answer: 'TEAL', clue: 'Blue-green color', difficulty: 'easy' },
      { answer: 'VIOLET', clue: 'Purple-blue color, also a flower name', difficulty: 'easy' },
      { answer: 'MAROON', clue: 'Dark brownish-red color', difficulty: 'hard' },
      { answer: 'CRIMSON', clue: 'Deep purplish-red color', difficulty: 'hard' },
      { answer: 'IVORY', clue: 'Off-white color like elephant tusks', difficulty: 'hard' },
      { answer: 'INDIGO', clue: 'Deep blue-purple color, one of the rainbow colors', difficulty: 'hard' },
      { answer: 'AMBER', clue: 'Orange-brown color like fossilized tree resin', difficulty: 'hard' },
      { answer: 'LAVENDER', clue: 'Pale purple color of a fragrant garden flower', difficulty: 'hard' },
      { answer: 'MAGENTA', clue: 'Vivid pinkish-purple color used in printing', difficulty: 'medium' },
      { answer: 'CYAN', clue: 'Bright blue-green color used in printing', difficulty: 'medium' },
      { answer: 'KHAKI', clue: 'Dull yellowish-brown color, often used in military uniforms', difficulty: 'medium' },
      { answer: 'CHARCOAL', clue: 'Very dark gray color, almost black', difficulty: 'medium' },
      { answer: 'AQUAMARINE', clue: 'Pale blue-green color like tropical sea water', difficulty: 'medium' }
    ],
    he: [
      { answer: 'אדום', clue: 'צבע הדם או תמרור עצור', difficulty: 'easy' },
      { answer: 'כחול', clue: 'צבע השמיים הבהירים', difficulty: 'easy' },
      { answer: 'ירוק', clue: 'צבע הדשא', difficulty: 'easy' },
      { answer: 'צהוב', clue: 'צבע הלימון', difficulty: 'easy' },
      { answer: 'שחור', clue: 'צבע הלילה, היעדר אור', difficulty: 'easy' },
      { answer: 'לבן', clue: 'צבע השלג', difficulty: 'easy' },
      { answer: 'סגול', clue: 'צבע המתקבל מערבוב אדום וכחול', difficulty: 'easy' },
      { answer: 'כתום', clue: 'צבע התפוז והגזר', difficulty: 'easy' },
      { answer: 'ורוד', clue: 'צבע אדמדם בהיר, מזוהה עם שושנים', difficulty: 'easy' },
      { answer: 'חום', clue: 'צבע הקפה או קליפת העץ', difficulty: 'easy' },
      { answer: 'אפור', clue: 'צבע שבין שחור ללבן', difficulty: 'easy' },
      { answer: 'זהב', clue: 'צבע מתכתי צהוב ומבריק', difficulty: 'easy' },
      { answer: 'כסף', clue: 'צבע מתכתי אפרפר ומבריק', difficulty: 'easy' },
      { answer: 'תכלת', clue: 'צבע כחול-ירקרק בהיר', difficulty: 'easy' },
      { answer: 'לילך', clue: 'צבע סגול-כחלחל, גם שם של פרח', difficulty: 'easy' },
      { answer: 'בורדו', clue: 'צבע אדום-חום כהה', difficulty: 'hard' },
      { answer: 'ארגמן', clue: 'צבע אדום-סגול עמוק', difficulty: 'hard' },
      { answer: 'שנהב', clue: 'צבע לבן-שמנת כמו חטי הפיל', difficulty: 'hard' },
      { answer: 'אינדיגו', clue: 'צבע כחול-סגול עמוק, אחד מצבעי הקשת', difficulty: 'hard' },
      { answer: 'ענבר', clue: 'צבע כתום-חום כמו שרף עץ מאובן', difficulty: 'hard' },
      { answer: 'לבנדר', clue: 'צבע סגול בהיר של פרח גן ריחני', difficulty: 'hard' },
      { answer: 'מגנטה', clue: 'צבע ורוד-סגול עז המשמש בהדפסה', difficulty: 'medium' },
      { answer: 'ציאן', clue: 'צבע כחול-ירוק בהיר המשמש בהדפסה', difficulty: 'medium' },
      { answer: 'חאקי', clue: 'צבע חום-צהבהב עמום, נפוץ במדים צבאיים', difficulty: 'medium' },
      { answer: 'פחם', clue: 'צבע אפור כהה מאוד, כמעט שחור', difficulty: 'medium' },
      { answer: 'אקוומרין', clue: 'צבע כחול-ירוק בהיר כמו מי ים טרופיים', difficulty: 'medium' }
    ],
    es: [
      { answer: 'ROJO', clue: 'Color de la sangre o una señal de alto', difficulty: 'easy' },
      { answer: 'AZUL', clue: 'Color de un cielo despejado', difficulty: 'easy' },
      { answer: 'VERDE', clue: 'Color del césped', difficulty: 'easy' },
      { answer: 'AMARILLO', clue: 'Color de un limón', difficulty: 'easy' },
      { answer: 'NEGRO', clue: 'Color de la noche, ausencia de luz', difficulty: 'easy' },
      { answer: 'BLANCO', clue: 'Color de la nieve', difficulty: 'easy' },
      { answer: 'MORADO', clue: 'Color hecho al mezclar rojo y azul', difficulty: 'easy' },
      { answer: 'NARANJA', clue: 'Color con nombre de una fruta cítrica', difficulty: 'easy' },
      { answer: 'ROSA', clue: 'Color rosado claro, asociado a las flores', difficulty: 'easy' },
      { answer: 'MARRON', clue: 'Color del café o la corteza de los árboles', difficulty: 'easy' },
      { answer: 'GRIS', clue: 'Color entre el negro y el blanco', difficulty: 'easy' },
      { answer: 'ORO', clue: 'Color metálico amarillo brillante', difficulty: 'easy' },
      { answer: 'PLATA', clue: 'Color metálico grisáceo brillante', difficulty: 'easy' },
      { answer: 'TURQUESA', clue: 'Color azul verdoso', difficulty: 'easy' },
      { answer: 'VIOLETA', clue: 'Color morado azulado, también una flor', difficulty: 'easy' },
      { answer: 'GRANATE', clue: 'Color rojo oscuro parecido al vino tinto', difficulty: 'hard' },
      { answer: 'CARMESI', clue: 'Color rojo intenso y profundo', difficulty: 'hard' },
      { answer: 'MARFIL', clue: 'Color blanco cremoso como los colmillos del elefante', difficulty: 'hard' },
      { answer: 'INDIGO', clue: 'Color azul violáceo profundo, uno de los colores del arcoíris', difficulty: 'hard' },
      { answer: 'AMBAR', clue: 'Color naranja-marrón como la resina de árbol fosilizada', difficulty: 'hard' },
      { answer: 'LAVANDA', clue: 'Color morado pálido de una flor de jardín aromática', difficulty: 'hard' },
      { answer: 'MAGENTA', clue: 'Color rosa-morado intenso usado en impresión', difficulty: 'medium' },
      { answer: 'CIAN', clue: 'Color azul-verdoso brillante usado en impresión', difficulty: 'medium' },
      { answer: 'CAQUI', clue: 'Color marrón amarillento apagado, usado a menudo en uniformes militares', difficulty: 'medium' },
      { answer: 'CARBON', clue: 'Color gris muy oscuro, casi negro', difficulty: 'medium' },
      { answer: 'AGUAMARINA', clue: 'Color azul verdoso pálido como el agua del mar tropical', difficulty: 'medium' }
    ]
  }
};

const STRINGS = {
  back:          { en: '← All Games',            he: 'כל המשחקים →',          es: '← Todos los juegos' },
  title:         { en: 'CROSSWORD',               he: 'תשבץ',                   es: 'CRUCIGRAMA' },
  tagline:       { en: 'Fill the grid using the clues — across and down',              he: 'מלאו את הלוח בעזרת החידות — מאוזן ומאונך',                 es: 'Completa la cuadrícula con las pistas — horizontal y vertical' },
  newPuzzle:     { en: 'New Crossword',           he: 'תשבץ חדש',               es: 'Nuevo Crucigrama' },
  restart:       { en: 'Restart',                 he: 'התחלה מחדש',             es: 'Reiniciar' },
  easy:          { en: 'Easy',                    he: 'קל',                     es: 'Fácil' },
  medium:        { en: 'Medium',                  he: 'בינוני',                 es: 'Medio' },
  hard:          { en: 'Hard',                    he: 'קשה',                    es: 'Difícil' },
  checkPuzzle:   { en: 'Check',                   he: 'בדיקה',                  es: 'Revisar' },
  hint:          { en: 'Hint',                    he: 'רמז',                    es: 'Pista' },
  across:        { en: 'ACROSS',                  he: 'מאוזן',                  es: 'HORIZONTAL' },
  down:          { en: 'DOWN',                     he: 'מאונך',                  es: 'VERTICAL' },
  solvedStat:    { en: 'Solved',                   he: 'נפתרו',                  es: 'Resueltos' },
  bestStat:      { en: 'Best',                     he: 'שיא',                    es: 'Mejor' },
  wonMsg:        { en: '🎉 Solved! Well done!',    he: '🎉 פתרתם! כל הכבוד!',    es: '🎉 ¡Resuelto! ¡Bien hecho!' },
  confirmReset:  { en: 'Start a new crossword? Current progress will be lost.', he: 'להתחיל תשבץ חדש? ההתקדמות הנוכחית תאבד.', es: '¿Empezar un nuevo crucigrama? Se perderá el progreso actual.' },
  confirmRestart: { en: 'Restart this crossword? Current progress will be lost.', he: 'להתחיל את התשבץ הזה מחדש? ההתקדמות הנוכחית תאבד.', es: '¿Reiniciar este crucigrama? Se perderá el progreso actual.' }
};
