// ── Clue bank ────────────────────────────────────────────────────────────
// Answers must be single, unbroken words (no spaces) — they get placed
// letter-by-letter into the grid. Clue text has no such restriction and can
// use normal accented characters freely.
// Hebrew: final letters (ם ן ף ך ץ) are normalized to base forms (מ נ פ כ צ)
// at grid-build time — same rule as wordsearch-strings.js's normalizeHebrew(),
// for the same reason (a final form could otherwise collide with a base
// form at a shared intersection cell).
// Spanish: answers avoid accented vowels and ñ so every letter matches
// cleanly at intersections (no accent-normalization helper needed).
const CLUE_BANK = {
  animals: {
    en: [
      { answer: 'LION', clue: 'King of the jungle' },
      { answer: 'TIGER', clue: 'Large striped big cat' },
      { answer: 'ELEPHANT', clue: 'Largest land animal, has a trunk' },
      { answer: 'BEAR', clue: 'Large, furry animal that hibernates in winter' },
      { answer: 'ZEBRA', clue: 'Black-and-white striped horse-like animal' },
      { answer: 'MONKEY', clue: 'Primate that loves bananas' },
      { answer: 'PENGUIN', clue: 'Flightless bird that lives in the cold' },
      { answer: 'DOLPHIN', clue: 'Intelligent marine mammal that clicks and whistles' },
      { answer: 'EAGLE', clue: 'Bird of prey with sharp eyesight' },
      { answer: 'RABBIT', clue: 'Long-eared hopping animal' },
      { answer: 'SNAKE', clue: 'Legless reptile that slithers' },
      { answer: 'TURTLE', clue: 'Reptile with a hard shell' },
      { answer: 'WOLF', clue: 'Wild canine that howls at the moon' },
      { answer: 'CAMEL', clue: 'Desert animal with humps' },
      { answer: 'KANGAROO', clue: 'Australian animal that hops and carries its young in a pouch' }
    ],
    he: [
      { answer: 'אריה', clue: 'מלך החיות' },
      { answer: 'טיגריס', clue: 'חתול גדול עם פסים' },
      { answer: 'פיל', clue: 'בעל החיים היבשתי הגדול בעולם, יש לו חדק' },
      { answer: 'דוב', clue: 'בעל חיים גדול ופרוותי שנכנס לחורף' },
      { answer: 'זברה', clue: 'דומה לסוס עם פסים שחורים ולבנים' },
      { answer: 'קוף', clue: 'פרימט שאוהב בננות' },
      { answer: 'פינגווין', clue: 'ציפור שלא עפה וחיה בקור' },
      { answer: 'דולפין', clue: 'יונק ים חכם המשמיע קליקים ושריקות' },
      { answer: 'נשר', clue: 'עוף דורס עם ראייה חדה' },
      { answer: 'ארנב', clue: 'בעל חיים עם אוזניים ארוכות שמקפץ' },
      { answer: 'נחש', clue: 'זוחל בלי רגליים שמתפתל' },
      { answer: 'צב', clue: 'זוחל עם שריון קשה' },
      { answer: 'זאב', clue: 'כלביים ברי שמייללים ללבנה' },
      { answer: 'גמל', clue: 'בעל חיים מדברי עם דבשות' },
      { answer: 'קנגורו', clue: 'בעל חיים אוסטרלי שמקפץ ונושא גורים בכיס' }
    ],
    es: [
      { answer: 'LEON', clue: 'Rey de la selva' },
      { answer: 'TIGRE', clue: 'Gran felino con rayas' },
      { answer: 'ELEFANTE', clue: 'El animal terrestre más grande, tiene trompa' },
      { answer: 'OSO', clue: 'Animal grande y peludo que hiberna en invierno' },
      { answer: 'CEBRA', clue: 'Animal con rayas blancas y negras' },
      { answer: 'MONO', clue: 'Primate que ama los plátanos' },
      { answer: 'PINGUINO', clue: 'Ave que no vuela y vive en el frío' },
      { answer: 'DELFIN', clue: 'Mamífero marino inteligente' },
      { answer: 'AGUILA', clue: 'Ave de presa con vista muy aguda' },
      { answer: 'CONEJO', clue: 'Animal de orejas largas que salta' },
      { answer: 'SERPIENTE', clue: 'Reptil sin patas que se arrastra' },
      { answer: 'TORTUGA', clue: 'Reptil con caparazón duro' },
      { answer: 'LOBO', clue: 'Cánido salvaje que aúlla a la luna' },
      { answer: 'CAMELLO', clue: 'Animal del desierto con jorobas' },
      { answer: 'CANGURO', clue: 'Animal australiano que salta y lleva crías en una bolsa' }
    ]
  },
  food: {
    en: [
      { answer: 'BREAD', clue: 'Baked staple made from flour' },
      { answer: 'CHEESE', clue: 'Dairy product made from milk curds' },
      { answer: 'PIZZA', clue: 'Italian dish with cheese and toppings on dough' },
      { answer: 'PASTA', clue: 'Italian noodles' },
      { answer: 'RICE', clue: 'Staple grain eaten worldwide' },
      { answer: 'HONEY', clue: 'Sweet substance made by bees' },
      { answer: 'BUTTER', clue: 'Dairy spread made from cream' },
      { answer: 'LEMON', clue: 'Sour yellow citrus fruit' },
      { answer: 'GARLIC', clue: 'Pungent bulb used for flavoring' },
      { answer: 'ONION', clue: 'Layered bulb that makes you cry when cut' },
      { answer: 'TOMATO', clue: 'Red fruit used in salads and sauces' },
      { answer: 'BANANA', clue: 'Long yellow tropical fruit' },
      { answer: 'CHOCOLATE', clue: 'Sweet treat made from cacao' },
      { answer: 'YOGURT', clue: 'Fermented dairy product' },
      { answer: 'SALAD', clue: 'Mix of raw vegetables' }
    ],
    he: [
      { answer: 'לחם', clue: 'מאכל בסיסי אפוי העשוי מקמח' },
      { answer: 'גבינה', clue: 'מוצר חלב העשוי מגבן' },
      { answer: 'פיצה', clue: 'מאכל איטלקי עם גבינה ותוספות על בסיס בצק' },
      { answer: 'פסטה', clue: 'אטריות איטלקיות' },
      { answer: 'אורז', clue: 'דגן בסיסי הנאכל בכל העולם' },
      { answer: 'דבש', clue: 'חומר מתוק שמכינות דבורים' },
      { answer: 'חמאה', clue: 'ממרח חלב העשוי משמנת' },
      { answer: 'לימון', clue: 'פרי הדר צהוב וחמוץ' },
      { answer: 'שום', clue: 'בצל חריף המשמש לתיבול' },
      { answer: 'בצל', clue: 'ירק שכבתי שמגרה דמעות בחיתוך' },
      { answer: 'עגבניה', clue: 'פרי אדום המשמש בסלטים ורטבים' },
      { answer: 'בננה', clue: 'פרי טרופי צהוב וארוך' },
      { answer: 'שוקולד', clue: 'ממתק העשוי מקקאו' },
      { answer: 'יוגורט', clue: 'מוצר חלב מותסס' },
      { answer: 'סלט', clue: 'תערובת של ירקות טריים' }
    ],
    es: [
      { answer: 'PAN', clue: 'Alimento básico horneado hecho de harina' },
      { answer: 'QUESO', clue: 'Producto lácteo hecho de leche cuajada' },
      { answer: 'PIZZA', clue: 'Plato italiano con queso sobre masa' },
      { answer: 'PASTA', clue: 'Fideos italianos' },
      { answer: 'ARROZ', clue: 'Grano básico comido en todo el mundo' },
      { answer: 'MIEL', clue: 'Sustancia dulce hecha por las abejas' },
      { answer: 'MANTEQUILLA', clue: 'Producto lácteo hecho de crema' },
      { answer: 'LIMON', clue: 'Fruta cítrica amarilla y ácida' },
      { answer: 'AJO', clue: 'Bulbo picante usado para dar sabor' },
      { answer: 'CEBOLLA', clue: 'Bulbo que hace llorar al cortarlo' },
      { answer: 'TOMATE', clue: 'Fruta roja usada en ensaladas y salsas' },
      { answer: 'PLATANO', clue: 'Fruta tropical larga y amarilla' },
      { answer: 'CHOCOLATE', clue: 'Dulce hecho de cacao' },
      { answer: 'YOGUR', clue: 'Producto lácteo fermentado' },
      { answer: 'ENSALADA', clue: 'Mezcla de verduras crudas' }
    ]
  },
  sports: {
    en: [
      { answer: 'SOCCER', clue: 'Sport played with a ball, mostly without hands' },
      { answer: 'TENNIS', clue: 'Racket sport played across a net' },
      { answer: 'BOXING', clue: 'Combat sport fought with fists' },
      { answer: 'GOLF', clue: 'Sport where you hit a small ball into holes' },
      { answer: 'HOCKEY', clue: 'Sport played with a stick and a puck' },
      { answer: 'RUGBY', clue: 'Contact sport with an oval ball' },
      { answer: 'SURFING', clue: 'Riding ocean waves on a board' },
      { answer: 'CYCLING', clue: 'Racing or riding on a bicycle' },
      { answer: 'SWIMMING', clue: 'Racing through water without a board' },
      { answer: 'BOWLING', clue: 'Knocking down pins with a heavy ball' },
      { answer: 'ARCHERY', clue: 'Sport of shooting arrows at a target' },
      { answer: 'FENCING', clue: 'Combat sport fought with swords' },
      { answer: 'SKIING', clue: 'Gliding downhill on snow with two long boards' },
      { answer: 'WRESTLING', clue: 'Combat sport of grappling and pins' },
      { answer: 'CLIMBING', clue: 'Sport of scaling rock walls or mountains' }
    ],
    he: [
      { answer: 'כדורגל', clue: 'ספורט המשוחק בכדור, בעיקר בלי ידיים' },
      { answer: 'טניס', clue: 'ספורט מחבטים המשוחק מעל רשת' },
      { answer: 'אגרוף', clue: 'ספורט קרב הנלחם באגרופים' },
      { answer: 'גולף', clue: 'ספורט של הכנסת כדור קטן לחורים' },
      { answer: 'הוקי', clue: 'ספורט המשוחק עם מקל ודיסקית' },
      { answer: 'רוגבי', clue: 'ספורט מגע עם כדור סגלגל' },
      { answer: 'גלישה', clue: 'רכיבה על גלי האוקיינוס בעזרת גלשן' },
      { answer: 'רכיבה', clue: 'תחרות או נסיעה על אופניים' },
      { answer: 'שחייה', clue: 'תחרות במים בלי גלשן' },
      { answer: 'באולינג', clue: 'הפלת כרעיים בעזרת כדור כבד' },
      { answer: 'קשתות', clue: 'ספורט של ירי חצים לעבר מטרה' },
      { answer: 'סייף', clue: 'ספורט קרב עם חרבות' },
      { answer: 'סקי', clue: 'גלישה במורד על שלג בעזרת שני מגלשים' },
      { answer: 'היאבקות', clue: 'ספורט קרב של תפיסות והצמדות' },
      { answer: 'טיפוס', clue: 'ספורט של טיפוס על קירות סלע או הרים' }
    ],
    es: [
      { answer: 'FUTBOL', clue: 'Deporte que se juega con un balón, casi sin usar las manos' },
      { answer: 'TENIS', clue: 'Deporte de raqueta que se juega sobre una red' },
      { answer: 'BOXEO', clue: 'Deporte de combate con los puños' },
      { answer: 'GOLF', clue: 'Deporte de golpear una pequeña bola hacia hoyos' },
      { answer: 'HOCKEY', clue: 'Deporte que se juega con un palo y un disco' },
      { answer: 'RUGBY', clue: 'Deporte de contacto con un balón ovalado' },
      { answer: 'SURF', clue: 'Deslizarse sobre las olas del mar en una tabla' },
      { answer: 'CICLISMO', clue: 'Correr o andar en bicicleta' },
      { answer: 'NATACION', clue: 'Nadar en competencia sin tabla' },
      { answer: 'BOLOS', clue: 'Derribar bolos con una bola pesada' },
      { answer: 'ARQUERIA', clue: 'Deporte de disparar flechas a un blanco' },
      { answer: 'ESGRIMA', clue: 'Deporte de combate con espadas' },
      { answer: 'ESQUI', clue: 'Deslizarse cuesta abajo en la nieve' },
      { answer: 'LUCHA', clue: 'Deporte de combate de agarres' },
      { answer: 'ESCALADA', clue: 'Deporte de subir muros de roca o montañas' }
    ]
  },
  science: {
    en: [
      { answer: 'ATOM', clue: 'Smallest unit of matter' },
      { answer: 'ENERGY', clue: 'Capacity to do work' },
      { answer: 'GRAVITY', clue: 'Force that pulls objects toward Earth' },
      { answer: 'OXYGEN', clue: 'Gas humans need to breathe' },
      { answer: 'CELL', clue: 'Basic unit of life' },
      { answer: 'VIRUS', clue: 'Microscopic infectious agent' },
      { answer: 'PLANET', clue: 'Large body orbiting a star' },
      { answer: 'GALAXY', clue: 'Huge system of stars, like the Milky Way' },
      { answer: 'MAGNET', clue: 'Object that attracts iron' },
      { answer: 'VACCINE', clue: 'Shot that trains the immune system' },
      { answer: 'CHEMISTRY', clue: 'Science of matter and reactions' },
      { answer: 'BIOLOGY', clue: 'Science of living things' },
      { answer: 'FOSSIL', clue: 'Preserved remains of ancient life' },
      { answer: 'BACTERIA', clue: 'Single-celled microorganisms' },
      { answer: 'ELECTRON', clue: 'Negatively charged subatomic particle' }
    ],
    he: [
      { answer: 'אטום', clue: 'היחידה הקטנה ביותר של החומר' },
      { answer: 'אנרגיה', clue: 'היכולת לבצע עבודה' },
      { answer: 'כבידה', clue: 'הכוח המושך חפצים לכיוון כדור הארץ' },
      { answer: 'חמצן', clue: 'הגז שבני אדם צריכים לנשום' },
      { answer: 'תא', clue: 'יחידת היסוד של החיים' },
      { answer: 'נגיף', clue: 'גורם מדבק מיקרוסקופי' },
      { answer: 'פלנטה', clue: 'גוף גדול המקיף כוכב' },
      { answer: 'גלקסיה', clue: 'מערכת עצומה של כוכבים' },
      { answer: 'מגנט', clue: 'חפץ המושך ברזל' },
      { answer: 'חיסון', clue: 'זריקה שמאמנת את מערכת החיסון' },
      { answer: 'כימיה', clue: 'מדע החומר והתגובות שלו' },
      { answer: 'ביולוגיה', clue: 'מדע היצורים החיים' },
      { answer: 'מאובן', clue: 'שרידים משומרים של חיים קדומים' },
      { answer: 'חיידק', clue: 'מיקרואורגניזם חד-תאי' },
      { answer: 'אלקטרון', clue: 'חלקיק תת-אטומי בעל מטען שלילי' }
    ],
    es: [
      { answer: 'ATOMO', clue: 'La unidad más pequeña de la materia' },
      { answer: 'ENERGIA', clue: 'Capacidad de realizar trabajo' },
      { answer: 'GRAVEDAD', clue: 'Fuerza que atrae los objetos hacia la Tierra' },
      { answer: 'OXIGENO', clue: 'Gas que los humanos necesitan para respirar' },
      { answer: 'CELULA', clue: 'Unidad básica de la vida' },
      { answer: 'VIRUS', clue: 'Agente infeccioso microscópico' },
      { answer: 'PLANETA', clue: 'Gran cuerpo que orbita una estrella' },
      { answer: 'GALAXIA', clue: 'Enorme sistema de estrellas' },
      { answer: 'IMAN', clue: 'Objeto que atrae el hierro' },
      { answer: 'VACUNA', clue: 'Inyección que entrena el sistema inmune' },
      { answer: 'QUIMICA', clue: 'Ciencia de la materia y sus reacciones' },
      { answer: 'BIOLOGIA', clue: 'Ciencia de los seres vivos' },
      { answer: 'FOSIL', clue: 'Restos conservados de vida antigua' },
      { answer: 'BACTERIA', clue: 'Microorganismo de una sola célula' },
      { answer: 'ELECTRON', clue: 'Partícula subatómica con carga negativa' }
    ]
  },
  geography: {
    en: [
      { answer: 'FRANCE', clue: 'European country famous for the Eiffel Tower' },
      { answer: 'JAPAN', clue: 'Island nation known as the Land of the Rising Sun' },
      { answer: 'BRAZIL', clue: 'Largest country in South America' },
      { answer: 'EGYPT', clue: 'Country famous for pyramids and the Nile' },
      { answer: 'CANADA', clue: 'Country north of the United States' },
      { answer: 'ITALY', clue: 'Boot-shaped country famous for pasta' },
      { answer: 'MEXICO', clue: 'Country south of the United States' },
      { answer: 'RUSSIA', clue: 'Largest country in the world by area' },
      { answer: 'CHINA', clue: 'Most populous country in Asia' },
      { answer: 'INDIA', clue: 'Country famous for the Taj Mahal' },
      { answer: 'GREECE', clue: 'Birthplace of the Olympic Games' },
      { answer: 'PERU', clue: 'Home to Machu Picchu and the Andes' },
      { answer: 'TURKEY', clue: 'Country that bridges Europe and Asia' },
      { answer: 'GERMANY', clue: 'European country known for Oktoberfest' },
      { answer: 'ISRAEL', clue: 'Country in the Middle East along the Mediterranean' }
    ],
    he: [
      { answer: 'צרפת', clue: 'מדינה אירופית ידועה במגדל אייפל' },
      { answer: 'יפן', clue: 'מדינת אי המכונה ארץ השמש העולה' },
      { answer: 'ברזיל', clue: 'המדינה הגדולה ביותר בדרום אמריקה' },
      { answer: 'מצרים', clue: 'מדינה ידועה בפירמידות ובנילוס' },
      { answer: 'קנדה', clue: 'מדינה שנמצאת מצפון לארצות הברית' },
      { answer: 'איטליה', clue: 'מדינה בצורת מגף, ידועה בפסטה' },
      { answer: 'מקסיקו', clue: 'מדינה שנמצאת מדרום לארצות הברית' },
      { answer: 'רוסיה', clue: 'המדינה הגדולה בעולם בשטח' },
      { answer: 'סין', clue: 'המדינה המאוכלסת ביותר באסיה' },
      { answer: 'הודו', clue: 'מדינה ידועה בטאג מהאל' },
      { answer: 'יוון', clue: 'מקום הולדתם של המשחקים האולימפיים' },
      { answer: 'פרו', clue: 'ביתם של מאצו פיצ׳ו והרי האנדים' },
      { answer: 'טורקיה', clue: 'מדינה המקשרת בין אירופה לאסיה' },
      { answer: 'גרמניה', clue: 'מדינה אירופית ידועה באוקטוברפסט' },
      { answer: 'ישראל', clue: 'מדינה במזרח התיכון על חוף הים התיכון' }
    ],
    es: [
      { answer: 'FRANCIA', clue: 'País europeo famoso por la Torre Eiffel' },
      { answer: 'JAPON', clue: 'Nación insular conocida como la Tierra del Sol Naciente' },
      { answer: 'BRASIL', clue: 'El país más grande de Sudamérica' },
      { answer: 'EGIPTO', clue: 'País famoso por sus pirámides y el río Nilo' },
      { answer: 'CANADA', clue: 'País al norte de Estados Unidos' },
      { answer: 'ITALIA', clue: 'País con forma de bota, famoso por la pasta' },
      { answer: 'MEXICO', clue: 'País al sur de Estados Unidos' },
      { answer: 'RUSIA', clue: 'El país más grande del mundo por área' },
      { answer: 'CHINA', clue: 'El país más poblado de Asia' },
      { answer: 'INDIA', clue: 'País famoso por el Taj Mahal' },
      { answer: 'GRECIA', clue: 'Cuna de los Juegos Olímpicos' },
      { answer: 'PERU', clue: 'Hogar de Machu Picchu y los Andes' },
      { answer: 'TURQUIA', clue: 'País que conecta Europa y Asia' },
      { answer: 'ALEMANIA', clue: 'País europeo conocido por el Oktoberfest' },
      { answer: 'ISRAEL', clue: 'País de Oriente Medio junto al Mediterráneo' }
    ]
  },
  colors: {
    en: [
      { answer: 'RED', clue: 'Color of blood or a stop sign' },
      { answer: 'BLUE', clue: 'Color of a clear sky' },
      { answer: 'GREEN', clue: 'Color of grass' },
      { answer: 'YELLOW', clue: 'Color of a lemon' },
      { answer: 'BLACK', clue: 'Color of night, the absence of light' },
      { answer: 'WHITE', clue: 'Color of snow' },
      { answer: 'PURPLE', clue: 'Color made by mixing red and blue' },
      { answer: 'ORANGE', clue: 'Color named after a citrus fruit' },
      { answer: 'PINK', clue: 'Pale reddish color, often linked to roses' },
      { answer: 'BROWN', clue: 'Color of coffee or tree bark' },
      { answer: 'GRAY', clue: 'Color between black and white' },
      { answer: 'GOLD', clue: 'Shiny yellow metallic color' },
      { answer: 'SILVER', clue: 'Shiny grayish metallic color' },
      { answer: 'TEAL', clue: 'Blue-green color' },
      { answer: 'VIOLET', clue: 'Purple-blue color, also a flower name' }
    ],
    he: [
      { answer: 'אדום', clue: 'צבע הדם או תמרור עצור' },
      { answer: 'כחול', clue: 'צבע השמיים הבהירים' },
      { answer: 'ירוק', clue: 'צבע הדשא' },
      { answer: 'צהוב', clue: 'צבע הלימון' },
      { answer: 'שחור', clue: 'צבע הלילה, היעדר אור' },
      { answer: 'לבן', clue: 'צבע השלג' },
      { answer: 'סגול', clue: 'צבע המתקבל מערבוב אדום וכחול' },
      { answer: 'כתום', clue: 'צבע הנקרא על שם פרי הדר' },
      { answer: 'ורוד', clue: 'צבע אדמדם בהיר, מזוהה עם שושנים' },
      { answer: 'חום', clue: 'צבע הקפה או קליפת העץ' },
      { answer: 'אפור', clue: 'צבע שבין שחור ללבן' },
      { answer: 'זהב', clue: 'צבע מתכתי צהוב ומבריק' },
      { answer: 'כסף', clue: 'צבע מתכתי אפרפר ומבריק' },
      { answer: 'תכלת', clue: 'צבע כחול-ירקרק בהיר' },
      { answer: 'לילך', clue: 'צבע סגול-כחלחל, גם שם של פרח' }
    ],
    es: [
      { answer: 'ROJO', clue: 'Color de la sangre o una señal de alto' },
      { answer: 'AZUL', clue: 'Color de un cielo despejado' },
      { answer: 'VERDE', clue: 'Color del césped' },
      { answer: 'AMARILLO', clue: 'Color de un limón' },
      { answer: 'NEGRO', clue: 'Color de la noche, ausencia de luz' },
      { answer: 'BLANCO', clue: 'Color de la nieve' },
      { answer: 'MORADO', clue: 'Color hecho al mezclar rojo y azul' },
      { answer: 'NARANJA', clue: 'Color con nombre de una fruta cítrica' },
      { answer: 'ROSA', clue: 'Color rosado claro, asociado a las flores' },
      { answer: 'MARRON', clue: 'Color del café o la corteza de los árboles' },
      { answer: 'GRIS', clue: 'Color entre el negro y el blanco' },
      { answer: 'ORO', clue: 'Color metálico amarillo brillante' },
      { answer: 'PLATA', clue: 'Color metálico grisáceo brillante' },
      { answer: 'TURQUESA', clue: 'Color azul verdoso' },
      { answer: 'VIOLETA', clue: 'Color morado azulado, también una flor' }
    ]
  }
};

const CATEGORIES = [
  { id: 'animals',   label: { en: '🐾 Animals',   he: '🐾 חיות',    es: '🐾 Animales' } },
  { id: 'food',      label: { en: '🍕 Food',      he: '🍕 אוכל',    es: '🍕 Comida' } },
  { id: 'sports',    label: { en: '🏅 Sports',    he: '🏅 ספורט',   es: '🏅 Deportes' } },
  { id: 'science',   label: { en: '🔬 Science',   he: '🔬 מדע',     es: '🔬 Ciencia' } },
  { id: 'geography', label: { en: '🌍 Geography', he: '🌍 גאוגרפיה', es: '🌍 Geografía' } },
  { id: 'colors',    label: { en: '🎨 Colors',    he: '🎨 צבעים',   es: '🎨 Colores' } }
];

const STRINGS = {
  back:          { en: '← All Games',            he: 'כל המשחקים →',          es: '← Todos los juegos' },
  title:         { en: 'CROSSWORD',               he: 'תשבץ',                   es: 'CRUCIGRAMA' },
  tagline:       { en: 'Fill the grid using the clues — across and down',              he: 'מלאו את הלוח בעזרת החידות — מאוזן ומאונך',                 es: 'Completa la cuadrícula con las pistas — horizontal y vertical' },
  newPuzzle:     { en: 'New Puzzle',              he: 'פאזל חדש',               es: 'Nuevo Puzzle' },
  checkPuzzle:   { en: 'Check',                   he: 'בדיקה',                  es: 'Revisar' },
  across:        { en: 'ACROSS',                  he: 'מאוזן',                  es: 'HORIZONTAL' },
  down:          { en: 'DOWN',                     he: 'מאונך',                  es: 'VERTICAL' },
  solvedStat:    { en: 'Solved',                   he: 'נפתרו',                  es: 'Resueltos' },
  bestStat:      { en: 'Best',                     he: 'שיא',                    es: 'Mejor' },
  wonMsg:        { en: '🎉 Solved! Well done!',    he: '🎉 פתרתם! כל הכבוד!',    es: '🎉 ¡Resuelto! ¡Bien hecho!' },
  confirmReset:  { en: 'Start a new puzzle? Current progress will be lost.', he: 'להתחיל פאזל חדש? ההתקדמות הנוכחית תאבד.', es: '¿Empezar un nuevo puzzle? Se perderá el progreso actual.' }
};
