// ── Clue bank ────────────────────────────────────────────────────────────
// Answers must be single, unbroken words (no spaces) — they get placed
// letter-by-letter into the grid. Clue text has no such restriction and can
// use normal accented characters freely.
// `clues` is a list, not a single string — every answer supports multiple
// alternate clues for the same definition; generateCrossword() picks one at
// random each time that word is placed, so replays don't always show the
// same wording for a repeated word. Most entries currently have just one;
// add more strings to the array to grow the variety for any given word.
// Hebrew: final letters (ם ן ף ך ץ) are normalized to base forms (מ נ פ כ צ)
// at grid-build time — same rule as wordsearch-strings.js's normalizeHebrew(),
// for the same reason (a final form could otherwise collide with a base
// form at a shared intersection cell).
// Spanish: answers avoid accented vowels and ñ so every letter matches
// cleanly at intersections (no accent-normalization helper needed).
const CLUE_BANK = {
  animals: {
    en: [
      { answer: 'LION', clues: ['King of the jungle', 'Big cat with a mane, found in Africa'], difficulty: 'easy' },
      { answer: 'TIGER', clues: ['Large striped big cat', 'Largest wild cat species, native to Asia'], difficulty: 'easy' },
      { answer: 'ELEPHANT', clues: ['Largest land animal, has a trunk', 'Huge gray mammal with large ears and tusks'], difficulty: 'easy' },
      { answer: 'BEAR', clues: ['Large, furry animal that hibernates in winter', 'Large mammal with a thick fur coat, found in forests and mountains'], difficulty: 'easy' },
      { answer: 'ZEBRA', clues: ['Black-and-white striped horse-like animal', 'African animal known for its unique stripe pattern'], difficulty: 'easy' },
      { answer: 'MONKEY', clues: ['Primate that loves bananas', 'Tree-climbing primate with a long tail'], difficulty: 'easy' },
      { answer: 'PENGUIN', clues: ['Flightless bird that lives in the cold', 'Black-and-white bird that swims but cannot fly'], difficulty: 'easy' },
      { answer: 'DOLPHIN', clues: ['Intelligent marine mammal that clicks and whistles', 'Playful sea mammal known for jumping out of the water'], difficulty: 'easy' },
      { answer: 'EAGLE', clues: ['Bird of prey with sharp eyesight', 'Majestic bird often used as a national symbol'], difficulty: 'easy' },
      { answer: 'RABBIT', clues: ['Long-eared hopping animal', 'Small furry animal that digs burrows underground'], difficulty: 'easy' },
      { answer: 'SNAKE', clues: ['Legless reptile that slithers', 'Reptile that sheds its skin as it grows'], difficulty: 'easy' },
      { answer: 'TURTLE', clues: ['Reptile with a hard shell', 'Slow-moving reptile that can retreat into its shell'], difficulty: 'easy' },
      { answer: 'WOLF', clues: ['Wild canine that howls at the moon', 'Pack-hunting canine, ancestor of the domestic dog'], difficulty: 'easy' },
      { answer: 'CAMEL', clues: ['Desert animal with humps', 'Animal well-suited for crossing hot, dry deserts'], difficulty: 'easy' },
      { answer: 'KANGAROO', clues: ['Australian animal that hops and carries its young in a pouch', 'Powerful-legged animal that can leap great distances'], difficulty: 'easy' },
      { answer: 'OCTOPUS', clues: ['Eight-armed sea creature with three hearts'], difficulty: 'hard' },
      { answer: 'CHAMELEON', clues: ['Lizard that changes color to blend in'], difficulty: 'hard' },
      { answer: 'RHINOCEROS', clues: ['Large thick-skinned animal with a horn on its nose'], difficulty: 'hard' },
      { answer: 'ARMADILLO', clues: ['Armored mammal that can roll into a ball'], difficulty: 'hard' },
      { answer: 'FLAMINGO', clues: ['Pink wading bird that stands on one leg'], difficulty: 'hard' },
      { answer: 'HEDGEHOG', clues: ['Small spiny mammal that curls into a ball'], difficulty: 'hard' },
      { answer: 'PANDA', clues: ['Black-and-white bear that eats mostly bamboo'], difficulty: 'medium' },
      { answer: 'GORILLA', clues: ['Large great ape found in African forests'], difficulty: 'medium' },
      { answer: 'OSTRICH', clues: ['Largest bird in the world, cannot fly'], difficulty: 'medium' },
      { answer: 'SQUIRREL', clues: ['Small bushy-tailed rodent that collects nuts'], difficulty: 'medium' },
      { answer: 'BUTTERFLY', clues: ['Insect with colorful wings that starts life as a caterpillar'], difficulty: 'medium' }
    ],
    he: [
      { answer: 'אריה', clues: ['מלך החיות', 'חתול גדול בעל רעמה, חי באפריקה'], difficulty: 'easy' },
      { answer: 'טיגריס', clues: ['חתול גדול עם פסים', 'מין החתולים הבר הגדול ביותר, מקורי לאסיה'], difficulty: 'easy' },
      { answer: 'פיל', clues: ['בעל החיים היבשתי הגדול בעולם, יש לו חדק', 'יונק אפור וענק עם אוזניים גדולות וחטים'], difficulty: 'easy' },
      { answer: 'דוב', clues: ['בעל חיים גדול ופרוותי שנכנס לחורף', 'יונק גדול עם פרווה עבה, חי ביערות ובהרים'], difficulty: 'easy' },
      { answer: 'זברה', clues: ['דומה לסוס עם פסים שחורים ולבנים', 'בעל חיים אפריקאי הידוע בדוגמת הפסים הייחודית שלו'], difficulty: 'easy' },
      { answer: 'קוף', clues: ['פרימט שאוהב בננות', 'פרימט מטפס עצים בעל זנב ארוך'], difficulty: 'easy' },
      { answer: 'פינגווין', clues: ['ציפור שלא עפה וחיה בקור', 'ציפור שחורה-לבנה ששוחה אך לא יכולה לעוף'], difficulty: 'easy' },
      { answer: 'דולפין', clues: ['יונק ים חכם המשמיע קליקים ושריקות', 'יונק ים שובב הידוע בקפיצותיו מעל המים'], difficulty: 'easy' },
      { answer: 'נשר', clues: ['עוף דורס עם ראייה חדה', 'ציפור מרשימה המשמשת לרוב כסמל לאומי'], difficulty: 'easy' },
      { answer: 'ארנב', clues: ['בעל חיים עם אוזניים ארוכות שמקפץ', 'בעל חיים קטן ופרוותי שחופר מחילות מתחת לאדמה'], difficulty: 'easy' },
      { answer: 'נחש', clues: ['זוחל בלי רגליים שמתפתל', 'זוחל שמפשיט את עורו ככל שהוא גדל'], difficulty: 'easy' },
      { answer: 'צב', clues: ['זוחל עם שריון קשה', 'זוחל אטי שיכול להסתתר בתוך שריונו'], difficulty: 'easy' },
      { answer: 'זאב', clues: ['כלביים ברי שמייללים ללבנה', 'כלבי שצד בלהקות, אבי הקדמון של הכלב הביתי'], difficulty: 'easy' },
      { answer: 'גמל', clues: ['בעל חיים מדברי עם דבשות', 'בעל חיים המותאם היטב לחציית מדבריות חמים ויבשים'], difficulty: 'easy' },
      { answer: 'קנגורו', clues: ['בעל חיים אוסטרלי שמקפץ ונושא גורים בכיס', 'בעל חיים עם רגליים חזקות שיכול לקפוץ מרחקים גדולים'], difficulty: 'easy' },
      { answer: 'תמנון', clues: ['יצור ימי בעל שמונה זרועות ושלושה לבבות'], difficulty: 'hard' },
      { answer: 'זיקית', clues: ['לטאה המחליפה צבע כדי להיטמע בסביבה'], difficulty: 'hard' },
      { answer: 'קרנף', clues: ['חיה גדולה בעלת עור עבה וקרן על האף'], difficulty: 'hard' },
      { answer: 'ארמדילו', clues: ['יונק משוריין שמסוגל להתגלגל לכדור'], difficulty: 'hard' },
      { answer: 'פלמינגו', clues: ['עוף ורוד החי במים רדודים ועומד על רגל אחת'], difficulty: 'hard' },
      { answer: 'קיפוד', clues: ['יונק קטן וקוצני שמתכרבל לכדור'], difficulty: 'hard' },
      { answer: 'פנדה', clues: ['דוב שחור-לבן שאוכל בעיקר במבוק'], difficulty: 'medium' },
      { answer: 'גורילה', clues: ['קוף אדם גדול החי ביערות אפריקה'], difficulty: 'medium' },
      { answer: 'יען', clues: ['הציפור הגדולה בעולם, לא יכולה לעוף'], difficulty: 'medium' },
      { answer: 'סנאי', clues: ['מכרסם קטן בעל זנב שעיר שאוסף אגוזים'], difficulty: 'medium' },
      { answer: 'פרפר', clues: ['חרק בעל כנפיים צבעוניות שמתחיל את חייו כזחל'], difficulty: 'medium' }
    ],
    es: [
      { answer: 'LEON', clues: ['Rey de la selva', 'Felino grande con melena, vive en África'], difficulty: 'easy' },
      { answer: 'TIGRE', clues: ['Gran felino con rayas', 'La especie de felino salvaje más grande, originaria de Asia'], difficulty: 'easy' },
      { answer: 'ELEFANTE', clues: ['El animal terrestre más grande, tiene trompa', 'Enorme mamífero gris con orejas grandes y colmillos'], difficulty: 'easy' },
      { answer: 'OSO', clues: ['Animal grande y peludo que hiberna en invierno', 'Mamífero grande con pelaje grueso, vive en bosques y montañas'], difficulty: 'easy' },
      { answer: 'CEBRA', clues: ['Animal con rayas blancas y negras', 'Animal africano conocido por su patrón único de rayas'], difficulty: 'easy' },
      { answer: 'MONO', clues: ['Primate que ama los plátanos', 'Primate trepador de árboles con una cola larga'], difficulty: 'easy' },
      { answer: 'PINGUINO', clues: ['Ave que no vuela y vive en el frío', 'Ave blanca y negra que nada pero no puede volar'], difficulty: 'easy' },
      { answer: 'DELFIN', clues: ['Mamífero marino inteligente', 'Mamífero marino juguetón conocido por saltar fuera del agua'], difficulty: 'easy' },
      { answer: 'AGUILA', clues: ['Ave de presa con vista muy aguda', 'Ave majestuosa usada a menudo como símbolo nacional'], difficulty: 'easy' },
      { answer: 'CONEJO', clues: ['Animal de orejas largas que salta', 'Pequeño animal peludo que cava madrigueras bajo tierra'], difficulty: 'easy' },
      { answer: 'SERPIENTE', clues: ['Reptil sin patas que se arrastra', 'Reptil que muda de piel a medida que crece'], difficulty: 'easy' },
      { answer: 'TORTUGA', clues: ['Reptil con caparazón duro', 'Reptil lento que puede esconderse dentro de su caparazón'], difficulty: 'easy' },
      { answer: 'LOBO', clues: ['Cánido salvaje que aúlla a la luna', 'Cánido que caza en manada, antepasado del perro doméstico'], difficulty: 'easy' },
      { answer: 'CAMELLO', clues: ['Animal del desierto con jorobas', 'Animal bien adaptado para cruzar desiertos calurosos y secos'], difficulty: 'easy' },
      { answer: 'CANGURO', clues: ['Animal australiano que salta y lleva crías en una bolsa', 'Animal de patas poderosas que puede saltar grandes distancias'], difficulty: 'easy' },
      { answer: 'PULPO', clues: ['Criatura marina con ocho brazos y tres corazones'], difficulty: 'hard' },
      { answer: 'CAMALEON', clues: ['Lagarto que cambia de color para camuflarse'], difficulty: 'hard' },
      { answer: 'RINOCERONTE', clues: ['Animal grande de piel gruesa con un cuerno en la nariz'], difficulty: 'hard' },
      { answer: 'ARMADILLO', clues: ['Mamífero acorazado que puede enrollarse en forma de bola'], difficulty: 'hard' },
      { answer: 'FLAMENCO', clues: ['Ave rosada que vive en aguas poco profundas y se para en una pata'], difficulty: 'hard' },
      { answer: 'ERIZO', clues: ['Pequeño mamífero espinoso que se enrolla en forma de bola'], difficulty: 'hard' },
      { answer: 'PANDA', clues: ['Oso blanco y negro que come principalmente bambú'], difficulty: 'medium' },
      { answer: 'GORILA', clues: ['Gran simio que vive en los bosques de África'], difficulty: 'medium' },
      { answer: 'AVESTRUZ', clues: ['El ave más grande del mundo, no puede volar'], difficulty: 'medium' },
      { answer: 'ARDILLA', clues: ['Pequeño roedor de cola peluda que recolecta nueces'], difficulty: 'medium' },
      { answer: 'MARIPOSA', clues: ['Insecto de alas coloridas que comienza su vida como oruga'], difficulty: 'medium' }
    ]
  },
  food: {
    en: [
      { answer: 'BREAD', clues: ['Baked staple made from flour', 'Baked food made by fermenting and baking dough'], difficulty: 'easy' },
      { answer: 'AVOCADO', clues: ['Creamy green fruit used to make guacamole', 'Pit-containing fruit often spread on toast'], difficulty: 'easy' },
      { answer: 'PIZZA', clues: ['Italian baked dish of dough topped with sauce and toppings', 'Round flatbread topped with sauce and vegetables, baked in an oven'], difficulty: 'easy' },
      { answer: 'PASTA', clues: ['Italian noodles', 'Dough shaped into strands or tubes, boiled before eating'], difficulty: 'easy' },
      { answer: 'RICE', clues: ['Staple grain eaten worldwide', 'Small white grain that\'s a staple across much of Asia'], difficulty: 'easy' },
      { answer: 'TOFU', clues: ['Soft protein-rich food made from soybeans', 'White, block-shaped food pressed from soy milk'], difficulty: 'easy' },
      { answer: 'LENTIL', clues: ['Small round legume often used in soups', 'Tiny disc-shaped seed, a common source of plant protein'], difficulty: 'easy' },
      { answer: 'LEMON', clues: ['Sour yellow citrus fruit', 'Tart yellow fruit often squeezed into drinks'], difficulty: 'easy' },
      { answer: 'GARLIC', clues: ['Pungent bulb used for flavoring', 'Strong-smelling bulb made of several small cloves'], difficulty: 'easy' },
      { answer: 'ONION', clues: ['Layered bulb that makes you cry when cut', 'Round bulb vegetable used as a base for many dishes'], difficulty: 'easy' },
      { answer: 'TOMATO', clues: ['Red fruit used in salads and sauces', 'Round red fruit often mistaken for a vegetable'], difficulty: 'easy' },
      { answer: 'BANANA', clues: ['Long yellow tropical fruit', 'Curved yellow fruit that grows in bunches'], difficulty: 'easy' },
      { answer: 'CHOCOLATE', clues: ['Sweet treat made from cacao', 'Sweet food made from roasted, ground cacao beans'], difficulty: 'easy' },
      { answer: 'SYRUP', clues: ['Sweet, thick liquid poured on pancakes, often made from maple sap', 'Thick sugary liquid used to sweeten drinks and desserts'], difficulty: 'easy' },
      { answer: 'SALAD', clues: ['Mix of raw vegetables', 'Cold dish of mixed vegetables, often with a dressing'], difficulty: 'easy' },
      { answer: 'ARTICHOKE', clues: ['Thistle-like vegetable eaten leaf by leaf'], difficulty: 'hard' },
      { answer: 'POMEGRANATE', clues: ['Red fruit filled with juicy seed clusters'], difficulty: 'hard' },
      { answer: 'ASPARAGUS', clues: ['Green stalk vegetable often grilled or steamed'], difficulty: 'hard' },
      { answer: 'CINNAMON', clues: ['Spice made from tree bark, used in baking'], difficulty: 'hard' },
      { answer: 'WATERMELON', clues: ['Large green fruit with red juicy flesh and seeds'], difficulty: 'hard' },
      { answer: 'EGGPLANT', clues: ['Purple oblong vegetable used in ratatouille and baba ganoush'], difficulty: 'hard' },
      { answer: 'SPINACH', clues: ['Leafy green vegetable rich in iron'], difficulty: 'medium' },
      { answer: 'MUSHROOM', clues: ['Fungus often sliced as a pizza topping'], difficulty: 'medium' },
      { answer: 'COCONUT', clues: ['Large brown tropical fruit with white flesh and milk inside'], difficulty: 'medium' },
      { answer: 'PINEAPPLE', clues: ['Spiky tropical fruit with a crown of leaves on top'], difficulty: 'medium' },
      { answer: 'PEPPER', clues: ['Vegetable that comes in red, green, and yellow varieties'], difficulty: 'medium' }
    ],
    he: [
      { answer: 'לחם', clues: ['מאכל בסיסי אפוי העשוי מקמח', 'מאכל אפוי המיוצר על ידי תסיסה ואפייה של בצק'], difficulty: 'easy' },
      { answer: 'אבוקדו', clues: ['פרי ירוק ושמנוני שממנו מכינים גואקמולי', 'פרי עם גרעין שלרוב מורחים על טוסט'], difficulty: 'easy' },
      { answer: 'פיצה', clues: ['מאכל איטלקי אפוי העשוי מבצק עם רוטב ותוספות', 'לחם שטוח ועגול עם רוטב וירקות, נאפה בתנור'], difficulty: 'easy' },
      { answer: 'פסטה', clues: ['אטריות איטלקיות', 'בצק שנוצר לרצועות או צינוריות, מבושל לפני האכילה'], difficulty: 'easy' },
      { answer: 'אורז', clues: ['דגן בסיסי הנאכל בכל העולם', 'גרגר לבן וקטן שהוא מזון בסיסי ברוב אסיה'], difficulty: 'easy' },
      { answer: 'טופו', clues: ['מאכל רך ועשיר בחלבון העשוי מפולי סויה', 'מאכל לבן בצורת קובייה, נדחס מחלב סויה'], difficulty: 'easy' },
      { answer: 'עדשה', clues: ['קטנית עגולה וקטנה המשמשת לרוב במרקים', 'זרע קטן בצורת עדשה, מקור נפוץ לחלבון צמחי'], difficulty: 'easy' },
      { answer: 'לימון', clues: ['פרי הדר צהוב וחמוץ', 'פרי צהוב וחמוץ שלרוב סוחטים לתוך משקאות'], difficulty: 'easy' },
      { answer: 'שום', clues: ['בצל חריף המשמש לתיבול', 'בצל בעל ריח חזק המורכב ממספר שיני קטנות'], difficulty: 'easy' },
      { answer: 'בצל', clues: ['ירק שכבתי שמגרה דמעות בחיתוך', 'ירק בצלי עגול המשמש כבסיס למאכלים רבים'], difficulty: 'easy' },
      { answer: 'עגבניה', clues: ['פרי אדום המשמש בסלטים ורטבים', 'פרי אדום ועגול שלעיתים קרובות טועים ומכנים אותו ירק'], difficulty: 'easy' },
      { answer: 'בננה', clues: ['פרי טרופי צהוב וארוך', 'פרי צהוב ומעוקל שגדל באשכולות'], difficulty: 'easy' },
      { answer: 'שוקולד', clues: ['ממתק העשוי מקקאו', 'ממתק העשוי מפולי קקאו קלויים וטחונים'], difficulty: 'easy' },
      { answer: 'סירופ', clues: ['נוזל מתוק וסמיך שיוצקים על פנקייק, לרוב עשוי ממיץ עץ המייפל', 'נוזל סמיך ומתוק המשמש להמתקת משקאות וקינוחים'], difficulty: 'easy' },
      { answer: 'סלט', clues: ['תערובת של ירקות טריים', 'מנה קרה של ירקות מעורבבים, לרוב עם רוטב'], difficulty: 'easy' },
      { answer: 'ארטישוק', clues: ['ירק דמוי קוץ שאוכלים עלה אחר עלה'], difficulty: 'hard' },
      { answer: 'רימון', clues: ['פרי אדום מלא בגרגרים עסיסיים'], difficulty: 'hard' },
      { answer: 'אספרגוס', clues: ['ירק גבעולי ירוק שלעיתים קרובות צולים או מאדים'], difficulty: 'hard' },
      { answer: 'קינמון', clues: ['תבלין העשוי מקליפת עץ, משמש באפייה'], difficulty: 'hard' },
      { answer: 'אבטיח', clues: ['פרי גדול וירוק עם בשר אדום ועסיסי וגרעינים'], difficulty: 'hard' },
      { answer: 'חציל', clues: ['ירק סגול ומוארך המשמש ברטטוי ובבבא גנוש'], difficulty: 'hard' },
      { answer: 'תרד', clues: ['ירק עלים ירוק עשיר בברזל'], difficulty: 'medium' },
      { answer: 'פטרייה', clues: ['מאכל הגדל ביערות, לא צמח ולא בעל חיים, נפוץ כתוספת לפיצה'], difficulty: 'medium' },
      { answer: 'קוקוס', clues: ['פרי טרופי חום וגדול עם בשר לבן וחלב בפנים'], difficulty: 'medium' },
      { answer: 'אננס', clues: ['פרי טרופי קוצני עם כתר עלים בראשו'], difficulty: 'medium' },
      { answer: 'פלפל', clues: ['ירק שמגיע בגוונים אדום, ירוק וצהוב'], difficulty: 'medium' }
    ],
    es: [
      { answer: 'PAN', clues: ['Alimento básico horneado hecho de harina', 'Alimento horneado hecho fermentando y horneando masa'], difficulty: 'easy' },
      { answer: 'AGUACATE', clues: ['Fruta verde y cremosa usada para hacer guacamole', 'Fruta con hueso que suele untarse en tostadas'], difficulty: 'easy' },
      { answer: 'PIZZA', clues: ['Plato italiano horneado hecho de masa con salsa y coberturas', 'Pan plano y redondo con salsa y verduras, horneado en el horno'], difficulty: 'easy' },
      { answer: 'PASTA', clues: ['Fideos italianos', 'Masa moldeada en tiras o tubos, hervida antes de comer'], difficulty: 'easy' },
      { answer: 'ARROZ', clues: ['Grano básico comido en todo el mundo', 'Pequeño grano blanco que es un alimento básico en gran parte de Asia'], difficulty: 'easy' },
      { answer: 'TOFU', clues: ['Alimento suave y rico en proteína hecho de soja', 'Alimento blanco en forma de bloque, prensado a partir de leche de soja'], difficulty: 'easy' },
      { answer: 'LENTEJA', clues: ['Legumbre pequeña y redonda usada a menudo en sopas', 'Semilla diminuta en forma de disco, una fuente común de proteína vegetal'], difficulty: 'easy' },
      { answer: 'LIMON', clues: ['Fruta cítrica amarilla y ácida', 'Fruta amarilla y ácida que suele exprimirse en bebidas'], difficulty: 'easy' },
      { answer: 'AJO', clues: ['Bulbo picante usado para dar sabor', 'Bulbo de olor fuerte formado por varios dientes pequeños'], difficulty: 'easy' },
      { answer: 'CEBOLLA', clues: ['Bulbo que hace llorar al cortarlo', 'Verdura bulbosa y redonda usada como base para muchos platos'], difficulty: 'easy' },
      { answer: 'TOMATE', clues: ['Fruta roja usada en ensaladas y salsas', 'Fruta roja y redonda que a menudo se confunde con una verdura'], difficulty: 'easy' },
      { answer: 'PLATANO', clues: ['Fruta tropical larga y amarilla', 'Fruta amarilla y curvada que crece en racimos'], difficulty: 'easy' },
      { answer: 'CHOCOLATE', clues: ['Dulce hecho de cacao', 'Dulce hecho de granos de cacao tostados y molidos'], difficulty: 'easy' },
      { answer: 'JARABE', clues: ['Líquido dulce y espeso que se vierte sobre panqueques, a menudo hecho de savia de arce', 'Líquido espeso y azucarado usado para endulzar bebidas y postres'], difficulty: 'easy' },
      { answer: 'ENSALADA', clues: ['Mezcla de verduras crudas', 'Plato frío de verduras mezcladas, a menudo con aderezo'], difficulty: 'easy' },
      { answer: 'ALCACHOFA', clues: ['Verdura parecida a un cardo que se come hoja por hoja'], difficulty: 'hard' },
      { answer: 'GRANADA', clues: ['Fruta roja llena de racimos de semillas jugosas'], difficulty: 'hard' },
      { answer: 'ESPARRAGO', clues: ['Verdura de tallo verde que suele asarse o cocerse al vapor'], difficulty: 'hard' },
      { answer: 'CANELA', clues: ['Especia hecha de corteza de árbol, usada en repostería'], difficulty: 'hard' },
      { answer: 'SANDIA', clues: ['Fruta grande y verde con pulpa roja y jugosa y semillas'], difficulty: 'hard' },
      { answer: 'BERENJENA', clues: ['Verdura morada y alargada usada en ratatouille y baba ganoush'], difficulty: 'hard' },
      { answer: 'ESPINACA', clues: ['Verdura de hoja verde rica en hierro'], difficulty: 'medium' },
      { answer: 'HONGO', clues: ['Organismo comestible, ni planta ni animal, usado como ingrediente en pizzas'], difficulty: 'medium' },
      { answer: 'COCO', clues: ['Fruta tropical grande y marrón con pulpa blanca y agua dentro'], difficulty: 'medium' },
      { answer: 'ANANAS', clues: ['Fruta tropical espinosa con una corona de hojas en la parte superior'], difficulty: 'medium' },
      { answer: 'PIMIENTO', clues: ['Verdura que viene en variedades roja, verde y amarilla'], difficulty: 'medium' }
    ]
  },
  sports: {
    en: [
      { answer: 'SOCCER', clues: ['Sport played with a ball, mostly without hands', 'World\'s most popular sport, played in two goals'], difficulty: 'easy' },
      { answer: 'TENNIS', clues: ['Racket sport played across a net', 'Sport played with rackets, a net, and a small ball'], difficulty: 'easy' },
      { answer: 'BOXING', clues: ['Combat sport fought with fists', 'Combat sport contested in a roped ring'], difficulty: 'easy' },
      { answer: 'GOLF', clues: ['Sport where you hit a small ball into holes', 'Outdoor sport played on a large grassy course with clubs'], difficulty: 'easy' },
      { answer: 'HOCKEY', clues: ['Sport played with a stick and a puck', 'Fast team sport played on ice or a field with sticks'], difficulty: 'easy' },
      { answer: 'RUGBY', clues: ['Contact sport with an oval ball', 'Physical team sport where players carry an oval ball forward'], difficulty: 'easy' },
      { answer: 'SURFING', clues: ['Riding ocean waves on a board', 'Water sport of standing on a board while riding waves'], difficulty: 'easy' },
      { answer: 'CYCLING', clues: ['Racing or riding on a bicycle', 'Sport of covering distance on two wheels'], difficulty: 'easy' },
      { answer: 'SWIMMING', clues: ['Racing through water without a board', 'Sport of propelling yourself through water using arms and legs'], difficulty: 'easy' },
      { answer: 'BOWLING', clues: ['Knocking down pins with a heavy ball', 'Indoor sport of rolling a heavy ball down a lane'], difficulty: 'easy' },
      { answer: 'ARCHERY', clues: ['Sport of shooting arrows at a target', 'Precision sport of hitting a distant target with arrows'], difficulty: 'easy' },
      { answer: 'FENCING', clues: ['Combat sport fought with swords', 'Olympic combat sport using thin blades'], difficulty: 'easy' },
      { answer: 'SKIING', clues: ['Gliding downhill on snow with two long boards', 'Winter sport of sliding down snowy slopes'], difficulty: 'easy' },
      { answer: 'WRESTLING', clues: ['Combat sport of grappling and pins', 'Ancient combat sport of grappling an opponent to the ground'], difficulty: 'easy' },
      { answer: 'CLIMBING', clues: ['Sport of scaling rock walls or mountains', 'Sport of ascending steep rock faces or artificial walls'], difficulty: 'easy' },
      { answer: 'BADMINTON', clues: ['Racket sport played with a shuttlecock'], difficulty: 'hard' },
      { answer: 'GYMNASTICS', clues: ['Sport of flips, balance beams, and floor routines'], difficulty: 'hard' },
      { answer: 'TRIATHLON', clues: ['Race combining swimming, cycling, and running'], difficulty: 'hard' },
      { answer: 'VOLLEYBALL', clues: ['Team sport played by hitting a ball over a net'], difficulty: 'hard' },
      { answer: 'HANDBALL', clues: ['Team sport where players throw a ball into a goal by hand'], difficulty: 'hard' },
      { answer: 'KARATE', clues: ['Japanese martial art of striking with hands and feet'], difficulty: 'hard' },
      { answer: 'CRICKET', clues: ['Bat-and-ball sport popular in England and India'], difficulty: 'medium' },
      { answer: 'RUNNING', clues: ['Sport of moving fast on foot, from sprints to marathons'], difficulty: 'medium' },
      { answer: 'SAILING', clues: ['Sport of racing boats powered by wind'], difficulty: 'medium' },
      { answer: 'DIVING', clues: ['Sport of jumping or descending into water'], difficulty: 'medium' },
      { answer: 'BASKETBALL', clues: ['Team sport played by shooting a ball through a hoop'], difficulty: 'medium' }
    ],
    he: [
      { answer: 'כדורגל', clues: ['ספורט המשוחק בכדור, בעיקר בלי ידיים', 'הספורט הפופולרי ביותר בעולם, משוחק לעבר שני שערים'], difficulty: 'easy' },
      { answer: 'טניס', clues: ['ספורט מחבטים המשוחק מעל רשת', 'ספורט המשוחק עם מחבטים, רשת וכדור קטן'], difficulty: 'easy' },
      { answer: 'אגרוף', clues: ['ספורט קרב הנלחם באגרופים', 'ספורט קרב המתקיים בזירה תחומה בחבלים'], difficulty: 'easy' },
      { answer: 'גולף', clues: ['ספורט של הכנסת כדור קטן לחורים', 'ספורט חוץ המשוחק על מגרש דשא גדול בעזרת מקלות'], difficulty: 'easy' },
      { answer: 'הוקי', clues: ['ספורט המשוחק עם מקל ודיסקית', 'ספורט קבוצתי מהיר המשוחק על קרח או מגרש בעזרת מקלות'], difficulty: 'easy' },
      { answer: 'רוגבי', clues: ['ספורט מגע עם כדור סגלגל', 'ספורט קבוצתי פיזי שבו שחקנים נושאים כדור סגלגל קדימה'], difficulty: 'easy' },
      { answer: 'גלישה', clues: ['רכיבה על גלי האוקיינוס בעזרת גלשן', 'ספורט מים של עמידה על גלשן תוך רכיבה על גלים'], difficulty: 'easy' },
      { answer: 'רכיבה', clues: ['תחרות או נסיעה על אופניים', 'ספורט של כיסוי מרחקים על שני גלגלים'], difficulty: 'easy' },
      { answer: 'שחייה', clues: ['תחרות במים בלי גלשן', 'ספורט של הנעה עצמית במים בעזרת ידיים ורגליים'], difficulty: 'easy' },
      { answer: 'באולינג', clues: ['הפלת כרעיים בעזרת כדור כבד', 'ספורט מקורה של גלגול כדור כבד במורד מסלול'], difficulty: 'easy' },
      { answer: 'קשתות', clues: ['ספורט של ירי חצים לעבר מטרה', 'ספורט דיוק של פגיעה במטרה מרוחקת בעזרת חצים'], difficulty: 'easy' },
      { answer: 'סייף', clues: ['ספורט קרב עם חרבות', 'ספורט קרב אולימפי המשתמש בלהבים דקים'], difficulty: 'easy' },
      { answer: 'סקי', clues: ['גלישה במורד על שלג בעזרת שני מגלשים', 'ספורט חורף של החלקה במורד מדרונות מושלגים'], difficulty: 'easy' },
      { answer: 'היאבקות', clues: ['ספורט קרב של תפיסות והצמדות', 'ספורט קרב עתיק של התגוששות עם יריב עד להפלתו'], difficulty: 'easy' },
      { answer: 'טיפוס', clues: ['ספורט של טיפוס על קירות סלע או הרים', 'ספורט של טיפוס על צוקים תלולים או קירות מלאכותיים'], difficulty: 'easy' },
      { answer: 'בדמינטון', clues: ['ספורט מחבטים המשוחק עם נוצית'], difficulty: 'hard' },
      { answer: 'התעמלות', clues: ['ספורט של סלטות, קורת שיווי משקל ותרגילי רצפה'], difficulty: 'hard' },
      { answer: 'טריאתלון', clues: ['תחרות המשלבת שחייה, רכיבה על אופניים וריצה'], difficulty: 'hard' },
      { answer: 'כדורעף', clues: ['ספורט קבוצתי המשוחק בהכאת כדור מעל רשת'], difficulty: 'hard' },
      { answer: 'כדוריד', clues: ['ספורט קבוצתי שבו שחקנים זורקים כדור לשער בעזרת היד'], difficulty: 'hard' },
      { answer: 'קראטה', clues: ['אמנות לחימה יפנית של הכאה בידיים וברגליים'], difficulty: 'hard' },
      { answer: 'קריקט', clues: ['ספורט מחבט וכדור פופולרי באנגליה ובהודו'], difficulty: 'medium' },
      { answer: 'ריצה', clues: ['ספורט של תנועה מהירה ברגל, מספרינטים ועד מרתונים'], difficulty: 'medium' },
      { answer: 'שייט', clues: ['ספורט של מרוצי סירות המונעות ברוח'], difficulty: 'medium' },
      { answer: 'צלילה', clues: ['ספורט של קפיצה או ירידה למים'], difficulty: 'medium' },
      { answer: 'כדורסל', clues: ['ספורט קבוצתי המשוחק בהכנסת כדור לסל'], difficulty: 'medium' }
    ],
    es: [
      { answer: 'FUTBOL', clues: ['Deporte que se juega con un balón, casi sin usar las manos', 'El deporte más popular del mundo, jugado hacia dos porterías'], difficulty: 'easy' },
      { answer: 'TENIS', clues: ['Deporte de raqueta que se juega sobre una red', 'Deporte jugado con raquetas, una red y una pelota pequeña'], difficulty: 'easy' },
      { answer: 'BOXEO', clues: ['Deporte de combate con los puños', 'Deporte de combate disputado en un cuadrilátero'], difficulty: 'easy' },
      { answer: 'GOLF', clues: ['Deporte de golpear una pequeña bola hacia hoyos', 'Deporte al aire libre jugado en un gran campo de césped con palos'], difficulty: 'easy' },
      { answer: 'HOCKEY', clues: ['Deporte que se juega con un palo y un disco', 'Deporte de equipo rápido jugado sobre hielo o campo con palos'], difficulty: 'easy' },
      { answer: 'RUGBY', clues: ['Deporte de contacto con un balón ovalado', 'Deporte de equipo físico donde los jugadores llevan un balón ovalado hacia adelante'], difficulty: 'easy' },
      { answer: 'SURF', clues: ['Deslizarse sobre las olas del mar en una tabla', 'Deporte acuático de pararse en una tabla mientras se montan olas'], difficulty: 'easy' },
      { answer: 'CICLISMO', clues: ['Correr o andar en bicicleta', 'Deporte de recorrer distancias sobre dos ruedas'], difficulty: 'easy' },
      { answer: 'NATACION', clues: ['Nadar en competencia sin tabla', 'Deporte de impulsarse a través del agua usando brazos y piernas'], difficulty: 'easy' },
      { answer: 'BOLOS', clues: ['Derribar bolos con una bola pesada', 'Deporte de interior de hacer rodar una bola pesada por una pista'], difficulty: 'easy' },
      { answer: 'ARQUERIA', clues: ['Deporte de disparar flechas a un blanco', 'Deporte de precisión de dar en un blanco lejano con flechas'], difficulty: 'easy' },
      { answer: 'ESGRIMA', clues: ['Deporte de combate con espadas', 'Deporte de combate olímpico que usa espadas delgadas'], difficulty: 'easy' },
      { answer: 'ESQUI', clues: ['Deslizarse cuesta abajo en la nieve', 'Deporte de invierno de deslizarse por laderas nevadas'], difficulty: 'easy' },
      { answer: 'LUCHA', clues: ['Deporte de combate de agarres', 'Antiguo deporte de combate de derribar a un oponente al suelo'], difficulty: 'easy' },
      { answer: 'ESCALADA', clues: ['Deporte de subir muros de roca o montañas', 'Deporte de ascender paredes rocosas empinadas o muros artificiales'], difficulty: 'easy' },
      { answer: 'BADMINTON', clues: ['Deporte de raqueta que se juega con un volante'], difficulty: 'hard' },
      { answer: 'GIMNASIA', clues: ['Deporte de saltos, barra de equilibrio y ejercicios de suelo'], difficulty: 'hard' },
      { answer: 'TRIATLON', clues: ['Carrera que combina natación, ciclismo y carrera a pie'], difficulty: 'hard' },
      { answer: 'VOLEIBOL', clues: ['Deporte de equipo que se juega golpeando un balón sobre una red'], difficulty: 'hard' },
      { answer: 'BALONMANO', clues: ['Deporte de equipo donde los jugadores lanzan un balón a la portería con la mano'], difficulty: 'hard' },
      { answer: 'KARATE', clues: ['Arte marcial japonés de golpear con las manos y los pies'], difficulty: 'hard' },
      { answer: 'CRICKET', clues: ['Deporte de bate y pelota popular en Inglaterra e India'], difficulty: 'medium' },
      { answer: 'CARRERA', clues: ['Deporte de moverse rápido a pie, desde sprints hasta maratones'], difficulty: 'medium' },
      { answer: 'VELA', clues: ['Deporte de carreras de barcos impulsados por el viento'], difficulty: 'medium' },
      { answer: 'BUCEO', clues: ['Deporte de saltar o descender al agua'], difficulty: 'medium' },
      { answer: 'BALONCESTO', clues: ['Deporte de equipo que se juega lanzando un balón por un aro'], difficulty: 'medium' }
    ]
  },
  science: {
    en: [
      { answer: 'ATOM', clues: ['Smallest unit of matter', 'Building block of matter made of protons, neutrons, and electrons'], difficulty: 'easy' },
      { answer: 'ENERGY', clues: ['Capacity to do work', 'What\'s needed to make things move, heat up, or light up'], difficulty: 'easy' },
      { answer: 'GRAVITY', clues: ['Force that pulls objects toward Earth', 'Invisible force that keeps planets in orbit and objects on the ground'], difficulty: 'easy' },
      { answer: 'OXYGEN', clues: ['Gas humans need to breathe', 'Colorless gas that makes up about 21% of Earth\'s atmosphere'], difficulty: 'easy' },
      { answer: 'CELL', clues: ['Basic unit of life', 'Microscopic structure that makes up every living organism'], difficulty: 'easy' },
      { answer: 'VIRUS', clues: ['Microscopic infectious agent', 'Tiny infectious particle that needs a host cell to reproduce'], difficulty: 'easy' },
      { answer: 'PLANET', clues: ['Large body orbiting a star', 'Round celestial body that travels around a sun'], difficulty: 'easy' },
      { answer: 'GALAXY', clues: ['Huge system of stars, like the Milky Way', 'Vast collection of stars, gas, and dust bound by gravity'], difficulty: 'easy' },
      { answer: 'MAGNET', clues: ['Object that attracts iron', 'Object with a field that pulls certain metals toward it'], difficulty: 'easy' },
      { answer: 'VACCINE', clues: ['Shot that trains the immune system', 'Medical injection that teaches the body to fight a disease'], difficulty: 'easy' },
      { answer: 'CHEMISTRY', clues: ['Science of matter and reactions', 'Branch of science studying how substances combine and change'], difficulty: 'easy' },
      { answer: 'BIOLOGY', clues: ['Science of living things', 'Branch of science that studies plants, animals, and other life'], difficulty: 'easy' },
      { answer: 'FOSSIL', clues: ['Preserved remains of ancient life', 'Ancient bones or imprints turned to stone over millions of years'], difficulty: 'easy' },
      { answer: 'BACTERIA', clues: ['Single-celled microorganisms', 'Microscopic single-celled organisms, some helpful and some harmful'], difficulty: 'easy' },
      { answer: 'ELECTRON', clues: ['Negatively charged subatomic particle', 'Tiny particle that orbits the nucleus of an atom'], difficulty: 'easy' },
      { answer: 'PHOTOSYNTHESIS', clues: ['Process plants use to turn sunlight into energy'], difficulty: 'hard' },
      { answer: 'EVOLUTION', clues: ['Gradual change in species over generations'], difficulty: 'hard' },
      { answer: 'MOLECULE', clues: ['Smallest unit of a chemical compound'], difficulty: 'hard' },
      { answer: 'ECOSYSTEM', clues: ['Community of organisms interacting with their environment'], difficulty: 'hard' },
      { answer: 'RADIATION', clues: ['Energy that travels as waves or particles'], difficulty: 'hard' },
      { answer: 'HORMONE', clues: ['Chemical messenger produced by glands in the body'], difficulty: 'hard' },
      { answer: 'FRICTION', clues: ['Force that resists motion between two surfaces'], difficulty: 'medium' },
      { answer: 'TELESCOPE', clues: ['Instrument used to observe distant objects in space'], difficulty: 'medium' },
      { answer: 'ORBIT', clues: ['Curved path an object follows around another due to gravity'], difficulty: 'medium' },
      { answer: 'CRYSTAL', clues: ['Solid with atoms arranged in a repeating pattern'], difficulty: 'medium' },
      { answer: 'METEOR', clues: ['Streak of light from a space rock burning in the atmosphere'], difficulty: 'medium' }
    ],
    he: [
      { answer: 'אטום', clues: ['היחידה הקטנה ביותר של החומר', 'אבן הבניין של החומר, המורכבת מפרוטונים, נויטרונים ואלקטרונים'], difficulty: 'easy' },
      { answer: 'אנרגיה', clues: ['היכולת לבצע עבודה', 'מה שנדרש כדי לגרום לדברים לנוע, להתחמם או להאיר'], difficulty: 'easy' },
      { answer: 'כבידה', clues: ['הכוח המושך חפצים לכיוון כדור הארץ', 'כוח בלתי נראה ששומר על כוכבי הלכת במסלולם ועל חפצים על הקרקע'], difficulty: 'easy' },
      { answer: 'חמצן', clues: ['הגז שבני אדם צריכים לנשום', 'גז חסר צבע המהווה כ-21% מהאטמוספרה של כדור הארץ'], difficulty: 'easy' },
      { answer: 'תא', clues: ['יחידת היסוד של החיים', 'מבנה מיקרוסקופי שממנו בנוי כל יצור חי'], difficulty: 'easy' },
      { answer: 'נגיף', clues: ['גורם מדבק מיקרוסקופי', 'חלקיק מדבק זעיר הזקוק לתא מארח כדי להתרבות'], difficulty: 'easy' },
      { answer: 'פלנטה', clues: ['גוף גדול המקיף כוכב', 'גוף שמימי עגול הנע סביב שמש'], difficulty: 'easy' },
      { answer: 'גלקסיה', clues: ['מערכת עצומה של כוכבים', 'אוסף עצום של כוכבים, גז ואבק המאוגדים בכוח הכבידה'], difficulty: 'easy' },
      { answer: 'מגנט', clues: ['חפץ המושך ברזל', 'חפץ בעל שדה המושך אליו מתכות מסוימות'], difficulty: 'easy' },
      { answer: 'חיסון', clues: ['זריקה שמאמנת את מערכת החיסון', 'זריקה רפואית המלמדת את הגוף להילחם במחלה'], difficulty: 'easy' },
      { answer: 'כימיה', clues: ['מדע החומר והתגובות שלו', 'ענף מדע החוקר כיצד חומרים משתלבים ומשתנים'], difficulty: 'easy' },
      { answer: 'ביולוגיה', clues: ['מדע היצורים החיים', 'ענף מדע החוקר צמחים, בעלי חיים וצורות חיים אחרות'], difficulty: 'easy' },
      { answer: 'מאובן', clues: ['שרידים משומרים של חיים קדומים', 'עצמות או טביעות עתיקות שהפכו לאבן על פני מיליוני שנים'], difficulty: 'easy' },
      { answer: 'חיידק', clues: ['מיקרואורגניזם חד-תאי', 'יצורים חד-תאיים מיקרוסקופיים, חלקם מועילים וחלקם מזיקים'], difficulty: 'easy' },
      { answer: 'אלקטרון', clues: ['חלקיק תת-אטומי בעל מטען שלילי', 'חלקיק זעיר החג סביב גרעין האטום'], difficulty: 'easy' },
      { answer: 'פוטוסינתזה', clues: ['התהליך שבו צמחים הופכים אור שמש לאנרגיה'], difficulty: 'hard' },
      { answer: 'אבולוציה', clues: ['שינוי הדרגתי במינים לאורך דורות'], difficulty: 'hard' },
      { answer: 'מולקולה', clues: ['היחידה הקטנה ביותר של תרכובת כימית'], difficulty: 'hard' },
      { answer: 'אקוסיסטמה', clues: ['קהילת יצורים המקיימת אינטראקציה עם סביבתה'], difficulty: 'hard' },
      { answer: 'קרינה', clues: ['אנרגיה הנעה בצורת גלים או חלקיקים'], difficulty: 'hard' },
      { answer: 'הורמון', clues: ['שליח כימי המיוצר על ידי בלוטות בגוף'], difficulty: 'hard' },
      { answer: 'חיכוך', clues: ['כוח המתנגד לתנועה בין שתי משטחים'], difficulty: 'medium' },
      { answer: 'טלסקופ', clues: ['מכשיר המשמש לצפייה בעצמים רחוקים בחלל'], difficulty: 'medium' },
      { answer: 'מסלול', clues: ['מסלול מעוקל שגוף עוקב אחריו סביב גוף אחר בגלל הכבידה'], difficulty: 'medium' },
      { answer: 'גביש', clues: ['מוצק שבו האטומים מסודרים בתבנית חוזרת'], difficulty: 'medium' },
      { answer: 'מטאור', clues: ['פס אור הנוצר משביט המתלקח באטמוספרה'], difficulty: 'medium' }
    ],
    es: [
      { answer: 'ATOMO', clues: ['La unidad más pequeña de la materia', 'Bloque fundamental de la materia formado por protones, neutrones y electrones'], difficulty: 'easy' },
      { answer: 'ENERGIA', clues: ['Capacidad de realizar trabajo', 'Lo que se necesita para hacer que las cosas se muevan, calienten o iluminen'], difficulty: 'easy' },
      { answer: 'GRAVEDAD', clues: ['Fuerza que atrae los objetos hacia la Tierra', 'Fuerza invisible que mantiene a los planetas en órbita y los objetos en el suelo'], difficulty: 'easy' },
      { answer: 'OXIGENO', clues: ['Gas que los humanos necesitan para respirar', 'Gas incoloro que constituye alrededor del 21% de la atmósfera terrestre'], difficulty: 'easy' },
      { answer: 'CELULA', clues: ['Unidad básica de la vida', 'Estructura microscópica que compone todo organismo vivo'], difficulty: 'easy' },
      { answer: 'VIRUS', clues: ['Agente infeccioso microscópico', 'Diminuta partícula infecciosa que necesita una célula huésped para reproducirse'], difficulty: 'easy' },
      { answer: 'PLANETA', clues: ['Gran cuerpo que orbita una estrella', 'Cuerpo celeste redondo que viaja alrededor de un sol'], difficulty: 'easy' },
      { answer: 'GALAXIA', clues: ['Enorme sistema de estrellas', 'Vasta colección de estrellas, gas y polvo unidos por la gravedad'], difficulty: 'easy' },
      { answer: 'IMAN', clues: ['Objeto que atrae el hierro', 'Objeto con un campo que atrae hacia sí ciertos metales'], difficulty: 'easy' },
      { answer: 'VACUNA', clues: ['Inyección que entrena el sistema inmune', 'Inyección médica que enseña al cuerpo a combatir una enfermedad'], difficulty: 'easy' },
      { answer: 'QUIMICA', clues: ['Ciencia de la materia y sus reacciones', 'Rama de la ciencia que estudia cómo se combinan y cambian las sustancias'], difficulty: 'easy' },
      { answer: 'BIOLOGIA', clues: ['Ciencia de los seres vivos', 'Rama de la ciencia que estudia plantas, animales y otras formas de vida'], difficulty: 'easy' },
      { answer: 'FOSIL', clues: ['Restos conservados de vida antigua', 'Huesos o huellas antiguas convertidas en piedra a lo largo de millones de años'], difficulty: 'easy' },
      { answer: 'BACTERIA', clues: ['Microorganismo de una sola célula', 'Organismos unicelulares microscópicos, algunos útiles y otros dañinos'], difficulty: 'easy' },
      { answer: 'ELECTRON', clues: ['Partícula subatómica con carga negativa', 'Partícula diminuta que orbita el núcleo de un átomo'], difficulty: 'easy' },
      { answer: 'FOTOSINTESIS', clues: ['Proceso que usan las plantas para convertir la luz solar en energía'], difficulty: 'hard' },
      { answer: 'EVOLUCION', clues: ['Cambio gradual en las especies a lo largo de generaciones'], difficulty: 'hard' },
      { answer: 'MOLECULA', clues: ['Unidad más pequeña de un compuesto químico'], difficulty: 'hard' },
      { answer: 'ECOSISTEMA', clues: ['Comunidad de organismos que interactúan con su entorno'], difficulty: 'hard' },
      { answer: 'RADIACION', clues: ['Energía que viaja en forma de ondas o partículas'], difficulty: 'hard' },
      { answer: 'HORMONA', clues: ['Mensajero químico producido por las glándulas del cuerpo'], difficulty: 'hard' },
      { answer: 'FRICCION', clues: ['Fuerza que se opone al movimiento entre dos superficies'], difficulty: 'medium' },
      { answer: 'TELESCOPIO', clues: ['Instrumento usado para observar objetos distantes en el espacio'], difficulty: 'medium' },
      { answer: 'ORBITA', clues: ['Trayectoria curva que sigue un objeto alrededor de otro por la gravedad'], difficulty: 'medium' },
      { answer: 'CRISTAL', clues: ['Sólido con átomos organizados en un patrón repetitivo'], difficulty: 'medium' },
      { answer: 'METEORO', clues: ['Rastro de luz de una roca espacial que se quema en la atmósfera'], difficulty: 'medium' }
    ]
  },
  geography: {
    en: [
      { answer: 'FRANCE', clues: ['European country famous for the Eiffel Tower', 'Country whose capital is Paris'], difficulty: 'easy' },
      { answer: 'JAPAN', clues: ['Island nation known as the Land of the Rising Sun', 'East Asian island country famous for sushi and Mount Fuji'], difficulty: 'easy' },
      { answer: 'BRAZIL', clues: ['Largest country in South America', 'South American country where Portuguese is the main language'], difficulty: 'easy' },
      { answer: 'EGYPT', clues: ['Country famous for pyramids and the Nile', 'North African country crossed by the Nile River'], difficulty: 'easy' },
      { answer: 'CANADA', clues: ['Country north of the United States', 'Second-largest country in the world by area, known for maple syrup'], difficulty: 'easy' },
      { answer: 'ITALY', clues: ['Boot-shaped country famous for pasta', 'European country home to Rome and the Colosseum'], difficulty: 'easy' },
      { answer: 'MEXICO', clues: ['Country south of the United States', 'North American country known for tacos and ancient pyramids'], difficulty: 'easy' },
      { answer: 'RUSSIA', clues: ['Largest country in the world by area', 'Country spanning both Europe and Asia, with Moscow as its capital'], difficulty: 'easy' },
      { answer: 'CHINA', clues: ['Most populous country in Asia', 'East Asian country home to the Great Wall'], difficulty: 'easy' },
      { answer: 'INDIA', clues: ['Country famous for the Taj Mahal', 'South Asian country where Hindi and English are widely spoken'], difficulty: 'easy' },
      { answer: 'GREECE', clues: ['Birthplace of the Olympic Games', 'European country known for ancient ruins and island beaches'], difficulty: 'easy' },
      { answer: 'PERU', clues: ['Home to Machu Picchu and the Andes', 'South American country home to the Inca ruins of Machu Picchu'], difficulty: 'easy' },
      { answer: 'TURKEY', clues: ['Country that bridges Europe and Asia', 'Country whose largest city, Istanbul, spans two continents'], difficulty: 'easy' },
      { answer: 'GERMANY', clues: ['European country known for Oktoberfest', 'European country known for cars, castles, and beer'], difficulty: 'easy' },
      { answer: 'ISRAEL', clues: ['Country in the Middle East along the Mediterranean', 'Country whose capital is Jerusalem'], difficulty: 'easy' },
      { answer: 'ARGENTINA', clues: ['South American country famous for tango'], difficulty: 'hard' },
      { answer: 'AUSTRALIA', clues: ['Country and continent known for kangaroos and koalas'], difficulty: 'hard' },
      { answer: 'NORWAY', clues: ['Scandinavian country known for fjords and the midnight sun'], difficulty: 'hard' },
      { answer: 'THAILAND', clues: ['Southeast Asian country known as the Land of Smiles'], difficulty: 'hard' },
      { answer: 'MOROCCO', clues: ['North African country known for its markets and the Sahara'], difficulty: 'hard' },
      { answer: 'ICELAND', clues: ['Nordic island nation of volcanoes and glaciers'], difficulty: 'hard' },
      { answer: 'PORTUGAL', clues: ['European country west of Spain, known for Porto and fado music'], difficulty: 'medium' },
      { answer: 'VIETNAM', clues: ['Southeast Asian country known for Ha Long Bay and pho soup'], difficulty: 'medium' },
      { answer: 'KENYA', clues: ['East African country famous for safaris and long-distance runners'], difficulty: 'medium' },
      { answer: 'SWEDEN', clues: ['Scandinavian country known for IKEA and Nobel Prizes'], difficulty: 'medium' },
      { answer: 'COLOMBIA', clues: ['South American country known for coffee and Cartagena'], difficulty: 'medium' }
    ],
    he: [
      { answer: 'צרפת', clues: ['מדינה אירופית ידועה במגדל אייפל', 'מדינה שבירתה פריז'], difficulty: 'easy' },
      { answer: 'יפן', clues: ['מדינת אי המכונה ארץ השמש העולה', 'מדינה במזרח אסיה הידועה בסושי ובהר פוג׳י'], difficulty: 'easy' },
      { answer: 'ברזיל', clues: ['המדינה הגדולה ביותר בדרום אמריקה', 'מדינה בדרום אמריקה שבה פורטוגזית היא השפה העיקרית'], difficulty: 'easy' },
      { answer: 'מצרים', clues: ['מדינה ידועה בפירמידות ובנילוס', 'מדינה בצפון אפריקה שנהר הנילוס חוצה אותה'], difficulty: 'easy' },
      { answer: 'קנדה', clues: ['מדינה שנמצאת מצפון לארצות הברית', 'המדינה השנייה בגודלה בעולם משטח, ידועה בסירופ המייפל שלה'], difficulty: 'easy' },
      { answer: 'איטליה', clues: ['מדינה בצורת מגף, ידועה בפסטה', 'מדינה אירופית שבה נמצאים רומא והקולוסיאום'], difficulty: 'easy' },
      { answer: 'מקסיקו', clues: ['מדינה שנמצאת מדרום לארצות הברית', 'מדינה בצפון אמריקה הידועה בטאקוס ובפירמידות עתיקות'], difficulty: 'easy' },
      { answer: 'רוסיה', clues: ['המדינה הגדולה בעולם בשטח', 'מדינה הפרושה על פני אירופה ואסיה, שבירתה מוסקבה'], difficulty: 'easy' },
      { answer: 'סין', clues: ['המדינה המאוכלסת ביותר באסיה', 'מדינה במזרח אסיה שבה נמצאת החומה הגדולה'], difficulty: 'easy' },
      { answer: 'הודו', clues: ['מדינה ידועה בטאג מהאל', 'מדינה בדרום אסיה שבה מדברים בהינדי ובאנגלית באופן נרחב'], difficulty: 'easy' },
      { answer: 'יוון', clues: ['מקום הולדתם של המשחקים האולימפיים', 'מדינה אירופית הידועה בחורבות עתיקות ובחופי אי'], difficulty: 'easy' },
      { answer: 'פרו', clues: ['ביתם של מאצו פיצ׳ו והרי האנדים', 'מדינה בדרום אמריקה שבה נמצאות חורבות האינקה של מאצו פיצ׳ו'], difficulty: 'easy' },
      { answer: 'טורקיה', clues: ['מדינה המקשרת בין אירופה לאסיה', 'מדינה שעירה הגדולה שלה, איסטנבול, פרוסה על פני שתי יבשות'], difficulty: 'easy' },
      { answer: 'גרמניה', clues: ['מדינה אירופית ידועה באוקטוברפסט', 'מדינה אירופית הידועה במכוניות, בטירות ובבירה'], difficulty: 'easy' },
      { answer: 'ישראל', clues: ['מדינה במזרח התיכון על חוף הים התיכון', 'מדינה שבירתה ירושלים'], difficulty: 'easy' },
      { answer: 'ארגנטינה', clues: ['מדינה בדרום אמריקה הידועה בריקוד הטנגו'], difficulty: 'hard' },
      { answer: 'אוסטרליה', clues: ['מדינה ויבשת הידועה בקנגורו ובקואלה'], difficulty: 'hard' },
      { answer: 'נורווגיה', clues: ['מדינה סקנדינבית הידועה בפיורדים ובשמש חצות'], difficulty: 'hard' },
      { answer: 'תאילנד', clues: ['מדינה בדרום מזרח אסיה המכונה ארץ החיוכים'], difficulty: 'hard' },
      { answer: 'מרוקו', clues: ['מדינה בצפון אפריקה הידועה בשווקים שלה ובמדבר סהרה'], difficulty: 'hard' },
      { answer: 'איסלנד', clues: ['מדינת אי נורדית של הרי געש וקרחונים'], difficulty: 'hard' },
      { answer: 'פורטוגל', clues: ['מדינה אירופית ממערב לספרד, ידועה בפורטו ובמוזיקת פאדו'], difficulty: 'medium' },
      { answer: 'וייטנאם', clues: ['מדינה בדרום מזרח אסיה הידועה במפרץ הלונג ובמרק פו'], difficulty: 'medium' },
      { answer: 'קניה', clues: ['מדינה במזרח אפריקה הידועה בספארי וברצי מרחקים ארוכים'], difficulty: 'medium' },
      { answer: 'שוודיה', clues: ['מדינה סקנדינבית הידועה באיקאה ובפרסי נובל'], difficulty: 'medium' },
      { answer: 'קולומביה', clues: ['מדינה בדרום אמריקה הידועה בקפה ובקרטחנה'], difficulty: 'medium' }
    ],
    es: [
      { answer: 'FRANCIA', clues: ['País europeo famoso por la Torre Eiffel', 'País cuya capital es París'], difficulty: 'easy' },
      { answer: 'JAPON', clues: ['Nación insular conocida como la Tierra del Sol Naciente', 'País insular del este de Asia famoso por el sushi y el monte Fuji'], difficulty: 'easy' },
      { answer: 'BRASIL', clues: ['El país más grande de Sudamérica', 'País sudamericano donde el portugués es el idioma principal'], difficulty: 'easy' },
      { answer: 'EGIPTO', clues: ['País famoso por sus pirámides y el río Nilo', 'País del norte de África atravesado por el río Nilo'], difficulty: 'easy' },
      { answer: 'CANADA', clues: ['País al norte de Estados Unidos', 'Segundo país más grande del mundo por área, conocido por el jarabe de arce'], difficulty: 'easy' },
      { answer: 'ITALIA', clues: ['País con forma de bota, famoso por la pasta', 'País europeo hogar de Roma y el Coliseo'], difficulty: 'easy' },
      { answer: 'MEXICO', clues: ['País al sur de Estados Unidos', 'País norteamericano conocido por los tacos y las antiguas pirámides'], difficulty: 'easy' },
      { answer: 'RUSIA', clues: ['El país más grande del mundo por área', 'País que abarca Europa y Asia, con Moscú como su capital'], difficulty: 'easy' },
      { answer: 'CHINA', clues: ['El país más poblado de Asia', 'País del este de Asia hogar de la Gran Muralla'], difficulty: 'easy' },
      { answer: 'INDIA', clues: ['País famoso por el Taj Mahal', 'País del sur de Asia donde se habla ampliamente hindi e inglés'], difficulty: 'easy' },
      { answer: 'GRECIA', clues: ['Cuna de los Juegos Olímpicos', 'País europeo conocido por sus ruinas antiguas y playas isleñas'], difficulty: 'easy' },
      { answer: 'PERU', clues: ['Hogar de Machu Picchu y los Andes', 'País sudamericano hogar de las ruinas incas de Machu Picchu'], difficulty: 'easy' },
      { answer: 'TURQUIA', clues: ['País que conecta Europa y Asia', 'País cuya ciudad más grande, Estambul, se extiende por dos continentes'], difficulty: 'easy' },
      { answer: 'ALEMANIA', clues: ['País europeo conocido por el Oktoberfest', 'País europeo conocido por sus autos, castillos y cerveza'], difficulty: 'easy' },
      { answer: 'ISRAEL', clues: ['País de Oriente Medio junto al Mediterráneo', 'País cuya capital es Jerusalén'], difficulty: 'easy' },
      { answer: 'ARGENTINA', clues: ['País sudamericano famoso por el tango'], difficulty: 'hard' },
      { answer: 'AUSTRALIA', clues: ['País y continente conocido por los canguros y koalas'], difficulty: 'hard' },
      { answer: 'NORUEGA', clues: ['País escandinavo conocido por sus fiordos y el sol de medianoche'], difficulty: 'hard' },
      { answer: 'TAILANDIA', clues: ['País del sudeste asiático conocido como la Tierra de las Sonrisas'], difficulty: 'hard' },
      { answer: 'MARRUECOS', clues: ['País del norte de África conocido por sus mercados y el Sahara'], difficulty: 'hard' },
      { answer: 'ISLANDIA', clues: ['Nación insular nórdica de volcanes y glaciares'], difficulty: 'hard' },
      { answer: 'PORTUGAL', clues: ['País europeo al oeste de España, conocido por Oporto y el fado'], difficulty: 'medium' },
      { answer: 'VIETNAM', clues: ['País del sudeste asiático conocido por la bahía de Ha Long y la sopa pho'], difficulty: 'medium' },
      { answer: 'KENIA', clues: ['País de África oriental famoso por los safaris y los corredores de fondo'], difficulty: 'medium' },
      { answer: 'SUECIA', clues: ['País escandinavo conocido por IKEA y los premios Nobel'], difficulty: 'medium' },
      { answer: 'COLOMBIA', clues: ['País sudamericano conocido por el café y Cartagena'], difficulty: 'medium' }
    ]
  },
  colors: {
    en: [
      { answer: 'RED', clues: ['Color of blood or a stop sign', 'Color often associated with danger or passion'], difficulty: 'easy' },
      { answer: 'BLUE', clues: ['Color of a clear sky', 'Color of the ocean on a calm day'], difficulty: 'easy' },
      { answer: 'GREEN', clues: ['Color of grass', 'Color associated with nature and growth'], difficulty: 'easy' },
      { answer: 'YELLOW', clues: ['Color of a lemon', 'Bright color of sunshine and daffodils'], difficulty: 'easy' },
      { answer: 'BLACK', clues: ['Color of night, the absence of light', 'Darkest possible color, opposite of white'], difficulty: 'easy' },
      { answer: 'WHITE', clues: ['Color of snow', 'Color that reflects all visible light'], difficulty: 'easy' },
      { answer: 'PURPLE', clues: ['Color made by mixing red and blue', 'Royal color between red and blue on the spectrum'], difficulty: 'easy' },
      { answer: 'ORANGE', clues: ['Color named after a citrus fruit', 'Warm color between red and yellow'], difficulty: 'easy' },
      { answer: 'PINK', clues: ['Pale reddish color, often linked to roses', 'Soft, pale shade of red, popular in nurseries'], difficulty: 'easy' },
      { answer: 'BROWN', clues: ['Color of coffee or tree bark', 'Earthy color of soil and tree trunks'], difficulty: 'easy' },
      { answer: 'GRAY', clues: ['Color between black and white', 'Neutral color of storm clouds'], difficulty: 'easy' },
      { answer: 'GOLD', clues: ['Shiny yellow metallic color', 'Precious metallic color awarded to first-place winners'], difficulty: 'easy' },
      { answer: 'SILVER', clues: ['Shiny grayish metallic color', 'Shiny metallic color awarded to second-place winners'], difficulty: 'easy' },
      { answer: 'TEAL', clues: ['Blue-green color', 'Blue-green color, deeper than turquoise'], difficulty: 'easy' },
      { answer: 'VIOLET', clues: ['Purple-blue color, also a flower name', 'Deep bluish-purple color at the end of the visible spectrum'], difficulty: 'easy' },
      { answer: 'MAROON', clues: ['Dark brownish-red color'], difficulty: 'hard' },
      { answer: 'CRIMSON', clues: ['Deep purplish-red color'], difficulty: 'hard' },
      { answer: 'IVORY', clues: ['Off-white color like elephant tusks'], difficulty: 'hard' },
      { answer: 'INDIGO', clues: ['Deep blue-purple color, one of the rainbow colors'], difficulty: 'hard' },
      { answer: 'AMBER', clues: ['Orange-brown color like fossilized tree resin'], difficulty: 'hard' },
      { answer: 'LAVENDER', clues: ['Pale purple color of a fragrant garden flower'], difficulty: 'hard' },
      { answer: 'MAGENTA', clues: ['Vivid pinkish-purple color used in printing'], difficulty: 'medium' },
      { answer: 'CYAN', clues: ['Bright blue-green color used in printing'], difficulty: 'medium' },
      { answer: 'KHAKI', clues: ['Dull yellowish-brown color, often used in military uniforms'], difficulty: 'medium' },
      { answer: 'CHARCOAL', clues: ['Very dark gray color, almost black'], difficulty: 'medium' },
      { answer: 'AQUAMARINE', clues: ['Pale blue-green color like tropical sea water'], difficulty: 'medium' }
    ],
    he: [
      { answer: 'אדום', clues: ['צבע הדם או תמרור עצור', 'צבע המזוהה לרוב עם סכנה או תשוקה'], difficulty: 'easy' },
      { answer: 'כחול', clues: ['צבע השמיים הבהירים', 'צבע האוקיינוס ביום שקט'], difficulty: 'easy' },
      { answer: 'ירוק', clues: ['צבע הדשא', 'צבע המזוהה עם הטבע והצמיחה'], difficulty: 'easy' },
      { answer: 'צהוב', clues: ['צבע הלימון', 'צבע בהיר של אור השמש ופרחי נרקיס'], difficulty: 'easy' },
      { answer: 'שחור', clues: ['צבע הלילה, היעדר אור', 'הצבע הכהה ביותר האפשרי, הפוך מלבן'], difficulty: 'easy' },
      { answer: 'לבן', clues: ['צבע השלג', 'צבע המשקף את כל האור הנראה לעין'], difficulty: 'easy' },
      { answer: 'סגול', clues: ['צבע המתקבל מערבוב אדום וכחול', 'צבע מלכותי הנמצא בין אדום לכחול בספקטרום'], difficulty: 'easy' },
      { answer: 'כתום', clues: ['צבע התפוז והגזר', 'צבע חם הנמצא בין אדום לצהוב'], difficulty: 'easy' },
      { answer: 'ורוד', clues: ['צבע אדמדם בהיר, מזוהה עם שושנים', 'גוון אדום עדין ובהיר, פופולרי בחדרי תינוקות'], difficulty: 'easy' },
      { answer: 'חום', clues: ['צבע הקפה או קליפת העץ', 'צבע אדמתי של קרקע וגזעי עצים'], difficulty: 'easy' },
      { answer: 'אפור', clues: ['צבע שבין שחור ללבן', 'צבע ניטרלי של עננֵי סערה'], difficulty: 'easy' },
      { answer: 'זהב', clues: ['צבע מתכתי צהוב ומבריק', 'צבע מתכתי יקר המוענק למקום הראשון בתחרויות'], difficulty: 'easy' },
      { answer: 'כסף', clues: ['צבע מתכתי אפרפר ומבריק', 'צבע מתכתי מבריק המוענק למקום השני בתחרויות'], difficulty: 'easy' },
      { answer: 'תכלת', clues: ['צבע כחול-ירקרק בהיר', 'צבע כחול-ירקרק, כחול השמיים הבהיר'], difficulty: 'easy' },
      { answer: 'לילך', clues: ['צבע סגול-כחלחל, גם שם של פרח', 'צבע סגול-כחלחל עמוק בקצה הספקטרום הנראה לעין'], difficulty: 'easy' },
      { answer: 'בורדו', clues: ['צבע אדום-חום כהה'], difficulty: 'hard' },
      { answer: 'ארגמן', clues: ['צבע אדום-סגול עמוק'], difficulty: 'hard' },
      { answer: 'שנהב', clues: ['צבע לבן-שמנת כמו חטי הפיל'], difficulty: 'hard' },
      { answer: 'אינדיגו', clues: ['צבע כחול-סגול עמוק, אחד מצבעי הקשת'], difficulty: 'hard' },
      { answer: 'ענבר', clues: ['צבע כתום-חום כמו שרף עץ מאובן'], difficulty: 'hard' },
      { answer: 'לבנדר', clues: ['צבע סגול בהיר של פרח גן ריחני'], difficulty: 'hard' },
      { answer: 'מגנטה', clues: ['צבע ורוד-סגול עז המשמש בהדפסה'], difficulty: 'medium' },
      { answer: 'ציאן', clues: ['צבע כחול-ירוק בהיר המשמש בהדפסה'], difficulty: 'medium' },
      { answer: 'חאקי', clues: ['צבע חום-צהבהב עמום, נפוץ במדים צבאיים'], difficulty: 'medium' },
      { answer: 'פחם', clues: ['צבע אפור כהה מאוד, כמעט שחור'], difficulty: 'medium' },
      { answer: 'אקוומרין', clues: ['צבע כחול-ירוק בהיר כמו מי ים טרופיים'], difficulty: 'medium' }
    ],
    es: [
      { answer: 'ROJO', clues: ['Color de la sangre o una señal de alto', 'Color a menudo asociado con el peligro o la pasión'], difficulty: 'easy' },
      { answer: 'AZUL', clues: ['Color de un cielo despejado', 'Color del océano en un día tranquilo'], difficulty: 'easy' },
      { answer: 'VERDE', clues: ['Color del césped', 'Color asociado con la naturaleza y el crecimiento'], difficulty: 'easy' },
      { answer: 'AMARILLO', clues: ['Color de un limón', 'Color brillante de la luz del sol y los narcisos'], difficulty: 'easy' },
      { answer: 'NEGRO', clues: ['Color de la noche, ausencia de luz', 'El color más oscuro posible, opuesto al blanco'], difficulty: 'easy' },
      { answer: 'BLANCO', clues: ['Color de la nieve', 'Color que refleja toda la luz visible'], difficulty: 'easy' },
      { answer: 'MORADO', clues: ['Color hecho al mezclar rojo y azul', 'Color real ubicado entre el rojo y el azul en el espectro'], difficulty: 'easy' },
      { answer: 'NARANJA', clues: ['Color con nombre de una fruta cítrica', 'Color cálido entre el rojo y el amarillo'], difficulty: 'easy' },
      { answer: 'ROSA', clues: ['Color rosado claro, asociado a las flores', 'Tono suave y pálido de rojo, popular en las habitaciones de bebés'], difficulty: 'easy' },
      { answer: 'MARRON', clues: ['Color del café o la corteza de los árboles', 'Color terroso de la tierra y los troncos de los árboles'], difficulty: 'easy' },
      { answer: 'GRIS', clues: ['Color entre el negro y el blanco', 'Color neutro de las nubes de tormenta'], difficulty: 'easy' },
      { answer: 'ORO', clues: ['Color metálico amarillo brillante', 'Color metálico precioso otorgado a los ganadores del primer lugar'], difficulty: 'easy' },
      { answer: 'PLATA', clues: ['Color metálico grisáceo brillante', 'Color metálico brillante otorgado a los ganadores del segundo lugar'], difficulty: 'easy' },
      { answer: 'TURQUESA', clues: ['Color azul verdoso', 'Color azul verdoso, más profundo que el turquesa'], difficulty: 'easy' },
      { answer: 'VIOLETA', clues: ['Color morado azulado, también una flor', 'Color morado azulado profundo al final del espectro visible'], difficulty: 'easy' },
      { answer: 'GRANATE', clues: ['Color rojo oscuro parecido al vino tinto'], difficulty: 'hard' },
      { answer: 'CARMESI', clues: ['Color rojo intenso y profundo'], difficulty: 'hard' },
      { answer: 'MARFIL', clues: ['Color blanco cremoso como los colmillos del elefante'], difficulty: 'hard' },
      { answer: 'INDIGO', clues: ['Color azul violáceo profundo, uno de los colores del arcoíris'], difficulty: 'hard' },
      { answer: 'AMBAR', clues: ['Color naranja-marrón como la resina de árbol fosilizada'], difficulty: 'hard' },
      { answer: 'LAVANDA', clues: ['Color morado pálido de una flor de jardín aromática'], difficulty: 'hard' },
      { answer: 'MAGENTA', clues: ['Color rosa-morado intenso usado en impresión'], difficulty: 'medium' },
      { answer: 'CIAN', clues: ['Color azul-verdoso brillante usado en impresión'], difficulty: 'medium' },
      { answer: 'CAQUI', clues: ['Color marrón amarillento apagado, usado a menudo en uniformes militares'], difficulty: 'medium' },
      { answer: 'CARBON', clues: ['Color gris muy oscuro, casi negro'], difficulty: 'medium' },
      { answer: 'AGUAMARINA', clues: ['Color azul verdoso pálido como el agua del mar tropical'], difficulty: 'medium' }
    ]
  }
};

const STRINGS = {
  back:          { en: '← All Games',            he: 'כל המשחקים →',          es: '← Todos los juegos' },
  title:         { en: 'CROSSWORD',               he: 'תשבץ',                   es: 'CRUCIGRAMA' },
  tagline:       { en: 'Fill the grid using the clues — across and down',              he: 'מלאו את הלוח בעזרת החידות — מאוזן ומאונך',                 es: 'Completa la cuadrícula con las pistas — horizontal y vertical' },
  newPuzzle:     { en: 'New Crossword',           he: 'תשבץ חדש',               es: 'Nuevo Crucigrama' },
  restart:       { en: 'Restart',                 he: 'התחלה מחדש',             es: 'Reiniciar' },
  easy:          { en: 'Easy',                    he: 'קל',                     es: 'Fácil' },
  medium:        { en: 'Medium',                  he: 'בינוני',                 es: 'Medio' },
  hard:          { en: 'Hard',                    he: 'קשה',                    es: 'Difícil' },
  checkPuzzle:   { en: 'Check',                   he: 'בדיקה',                  es: 'Revisar' },
  hint:          { en: 'Hint',                    he: 'רמז',                    es: 'Pista' },
  across:        { en: 'ACROSS',                  he: 'מאוזן',                  es: 'HORIZONTAL' },
  down:          { en: 'DOWN',                     he: 'מאונך',                  es: 'VERTICAL' },
  solvedStat:    { en: 'Solved',                   he: 'נפתרו',                  es: 'Resueltos' },
  bestStat:      { en: 'Best',                     he: 'שיא',                    es: 'Mejor' },
  wonMsg:        { en: '🎉 Solved! Well done!',    he: '🎉 פתרתם! כל הכבוד!',    es: '🎉 ¡Resuelto! ¡Bien hecho!' },
  confirmReset:  { en: 'Start a new crossword? Current progress will be lost.', he: 'להתחיל תשבץ חדש? ההתקדמות הנוכחית תאבד.', es: '¿Empezar un nuevo crucigrama? Se perderá el progreso actual.' },
  confirmRestart: { en: 'Restart this crossword? Current progress will be lost.', he: 'להתחיל את התשבץ הזה מחדש? ההתקדמות הנוכחית תאבד.', es: '¿Reiniciar este crucigrama? Se perderá el progreso actual.' }
};
